{
  "hash": "9efb2ca709390d913288662379397726",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Bounded Correlation Matrices: Sign Constraints, Finite Boxes, and Exact Values\"\nauthor: \"Sean Pinkney\"\ndate: \"2026-08-08\"\ncategories: [stan, correlation, parameterizations]\nbibliography: references.bib\nresources:\n  - benchmark_bounds.R\n  - benchmark_fixed_values.R\n  - tri-sign-corr-bounds.stan\n  - global-ray-corr-bounds.stan\n  - direct-certified-box-corr.stan\n  - bounds-run-settings.csv\n  - bounds-source-hashes.csv\n  - fixed-values-run-settings.csv\n  - fixed-values-source-hashes.csv\n  - bounds-cell-summary.csv\n  - bounds-diagnostics.csv\n  - bounds-scenarios.csv\n  - bounds-selected-draws.csv\n  - fixed-values-diagnostics.csv\n  - fixed-values-summary.csv\nformat:\n  html:\n    code-fold: true\n---\n\n## 1. From Structural Zeros to Bounds\n\nMy [previous post](../post-11-corr-zeros-bakeoff/corr-zeros-bakeoff.qmd) used a triangular basis to sample correlation matrices with exact structural zeros. Given the preceding Cholesky rows, each zero is a homogeneous linear constraint on the current row, and the zero vector remains an admissible row completion after every valid prefix. Here I ask how much of that construction carries over to prescribed signs, finite cell-specific intervals, and exact nonzero values.\n\nI ended up with three different cases.\n\n1.  **Prescribed signs admit a smooth triangular transform.** Zeros define subspaces; signs define cones. Replacing the free coordinates in each Cholesky row by coordinates inside the requested sign cone gives a bijection onto the interior of the sign-constrained correlation space. Section 3 gives the row-wise inverse.\n\n2.  **Finite boxes do not fit the same homogeneous construction.** A box such as $0.2 < \\Omega_{21} < 0.5$ is not scale invariant, so the linear zero basis does not represent it. For this case, I use rays from a strictly feasible anchor. Section 4 shows that the resulting map covers the interior of the box--elliptope intersection, apart from the anchor itself. Its active boundary can change with direction and create gradient kinks.\n\n3.  **An exact nonzero value is an affine equality.** A translated version of the zero-row construction exists, but its available radius depends on earlier correlations and can disappear after an otherwise valid prefix. For general fixed-value patterns, I instead remove the fixed coordinates from the global anchor-ray map.\n\nThroughout, the LKJ shape $\\eta>0$ is fixed. The target is an LKJ density [@lewandowski2009] restricted to the requested ordinary-correlation region,\n\n$$\\pi(\\Omega) \\propto \\det(\\Omega)^{\\eta-1}\n  \\mathbf 1\\{\\ell_{ij}<\\Omega_{ij}<u_{ij}\\},$$\n\nwith respect to Lebesgue measure on the free lower-triangular correlations. For positive-width free bounds, endpoint faces have measure zero, so open and closed interval notation induce the same continuous distribution.\n\nWhen some correlations are fixed exactly, I instead define the density with respect to the remaining free ordinary-correlation coordinates. This is a lower-dimensional target, not an unnormalized positive-width indicator with equal endpoints. Any shrinking-interval argument must keep its width-dependent normalizing constant.\n\nThe general look-ahead C-vine [implementation](https://gist.github.com/spinkney/7d994fb03079c9edb8a0e83a40d2faad/d13345baceadce5062dc61ebb24cb9c08a87eba7) and my earlier entry-wise Cholesky construction [@pinkney2024] provide sequential ways to target bounded densities, although a later feasible interval can be empty. Here I focus on transforms that make *global* feasibility explicit, so a sequential construction does not encounter a nonlocal boundary late.\n\n## 2. Why the Zero-Basis Construction Does Not Extend Directly\n\nWrite $\\Omega=LL'$ and consider row $i$. Let\n\n$$B=L_{1:(i-1),1:(i-1)}, \\qquad\nv=L_{i,1:(i-1)}', \\qquad\nc=\\Omega_{i,1:(i-1)}'.$$\n\nThe ordinary correlations in the row satisfy\n\n$$c=Bv,$$\n\nand positive definiteness requires $v'v<1$ so that $L_{ii}=\\sqrt{1-v'v}>0$. Therefore the feasible set for $c$ given the previous rows is the Schur ellipsoid\n\n$$\\mathcal E_B=\\{c:c'(BB')^{-1}c<1\\}.$$\n\nAn exact zero selects a linear slice through this ellipsoid. To see what this buys, let $d=i-1$ and suppose that the entries indexed by $Z=\\{j_1,\\ldots,j_m\\}\\subseteq\\{1,\\ldots,d\\}$ are fixed to zero. Define the coordinate-selection matrix $P_Z\\in\\mathbb R^{m\\times d}$ by taking its $r$th row to be the transpose of the $j_r$th standard basis vector, $e_{j_r}'$. Thus, for any $x\\in\\mathbb R^d$,\n\n$$P_Zx=(x_{j_1},\\ldots,x_{j_m})'.$$\n\nMultiplication by $P_Z$ simply extracts the coordinates indexed by $Z$. The $m$ zero constraints can therefore be collected as\n\n$$P_Zc=P_ZBv=0.$$\n\nThese are homogeneous linear equations in $v$. The leading Cholesky block $B$ is nonsingular, so the selected rows $P_ZB$ are linearly independent and have rank $m$. The constraints therefore remove exactly $m$ degrees of freedom and leave the $(d-m)$-dimensional subspace $\\ker(P_ZB)$. The orthogonal-complement construction of @axen2023 and the triangular construction from my previous post span this same nullspace, but they choose its basis differently. The former computes a complement to the constrained rows. The latter ties the basis to the free entries of the Cholesky row: for each free coordinate, it sets that coordinate to one and the other free coordinates to zero, solves the constrained coordinates by back-substitution, and then orthonormalizes the resulting basis.\n\nIf $Q$ denotes either orthonormal basis, write $v=Qz$, so that $v'v=z'z$. One can then sample $z$ in the open unit ball in $\\mathbb R^{d-m}$ and set\n\n$$L_{ii}=\\sqrt{1-z'z}.$$\n\nThe pair $(z,L_{ii})$ lies on a $(d-m)$-dimensional unit hemisphere, and multiplication by $Q$ lifts $z$ into the original off-diagonal coordinates $v$. Every lifted row satisfies the zero constraints automatically, and every feasible row in the constrained subspace has such a representation. Thus the basis construction does more than enforce the zeros: it removes exactly the coordinates that the equalities have made redundant while retaining the usual hemisphere parameterization of a unit-norm Cholesky row.\n\nBounds instead produce\n\n$$\\mathcal E_B \\cap \\{c:\\ell<c<u\\},$$\n\nan ellipsoid intersected with slabs. Assume here that every interval has positive width. Both the Schur ellipsoid and the open box $\\{c:\\ell<c<u\\}$ are open subsets of $\\mathbb R^d$, so whenever their intersection is nonempty, every feasible point has a sufficiently small $d$-dimensional neighborhood that remains feasible. The bounds can truncate the allowable range along a direction, but they do not remove a local degree of freedom as an equality does.\n\nThey also change the boundary geometry. In the closure of the feasible set, a bound that is reached before the positive-definite boundary contributes a flat codimension-one face $c_j=\\ell_j$ or $c_j=u_j$. Several active bounds can meet in edges or corners, while the condition $c'(BB')^{-1}c=1$ contributes the curved ellipsoid boundary. Which piece is encountered first depends on the point and direction. There is therefore no fixed lower-dimensional subspace whose basis encodes the interval constraints: removing a basis column handles an equality, whereas an inequality must retain the coordinate and control how far it may move. The column-removal step used for exact zeros consequently does not impose these bounds by itself. Clipping correlations after the transform would change the induced density and can also break positive definiteness.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nsource(\"../../R/theme_blog.R\")\n\nschur_constraint_plot <- local({\n  previous_block <- matrix(\n    c(\n      1.0, 0.5, 0.5,\n      0.5, 1.0, 0.5,\n      0.5, 0.5, 1.0\n    ),\n    nrow = 3,\n    byrow = TRUE\n  )\n  previous_cholesky <- chol(previous_block)\n\n  lower_bound <- 0.55\n  upper_bound <- 0.85\n  fixed_nonzero <- 0.70\n  lower_free_radius <- sqrt(1 - lower_bound^2)\n  upper_free_radius <- sqrt(1 - upper_bound^2)\n  fixed_free_radius <- sqrt(1 - fixed_nonzero^2)\n\n  zero_panel <- paste(\n    \"Exact zero:  c₁ = 0\",\n    \"2D linear section\",\n    \"0² + free² < 1;  free radius = 1.00\",\n    sep = \"\\n\"\n  )\n  bound_panel <- paste(\n    \"Finite bound:  0.55 < c₁ < 0.85\",\n    \"3D off-origin volume\",\n    sprintf(\n      \"free radius varies: %.2f down to %.2f\",\n      lower_free_radius,\n      upper_free_radius\n    ),\n    sep = \"\\n\"\n  )\n  nonzero_panel <- paste(\n    \"Exact nonzero:  c₁ = 0.70\",\n    \"2D affine section\",\n    sprintf(\n      \"0.70² + free² < 1;  free radius = %.2f\",\n      fixed_free_radius\n    ),\n    sep = \"\\n\"\n  )\n  panel_levels <- c(zero_panel, bound_panel, nonzero_panel)\n\n  stopifnot(\n    min(eigen(\n      previous_block,\n      symmetric = TRUE,\n      only.values = TRUE\n    )$values) > 0,\n    -1 < lower_bound,\n    lower_bound < upper_bound,\n    upper_bound < 1,\n    0 < fixed_nonzero,\n    fixed_nonzero < 1\n  )\n\n  azimuth <- 72 * pi / 180\n  elevation <- 30 * pi / 180\n  roll <- -14 * pi / 180\n  right <- c(-sin(azimuth), cos(azimuth), 0)\n  up <- c(\n    -sin(elevation) * cos(azimuth),\n    -sin(elevation) * sin(azimuth),\n    cos(elevation)\n  )\n\n  project_3d <- function(points) {\n    projected <- as.matrix(points) %*% cbind(right, up)\n    data.frame(\n      x = cos(roll) * projected[, 1] -\n        sin(roll) * projected[, 2],\n      y = sin(roll) * projected[, 1] +\n        cos(roll) * projected[, 2]\n    )\n  }\n\n  ellipsoid_section <- function(value, n = 481) {\n    angle <- seq(0, 2 * pi, length.out = n)\n    radius <- sqrt(1 - value^2)\n    sphere_section <- cbind(\n      value,\n      radius * cos(angle),\n      radius * sin(angle)\n    )\n    sphere_section %*% previous_cholesky\n  }\n\n  section_check <- ellipsoid_section(fixed_nonzero)\n  previous_precision <- solve(previous_block)\n  stopifnot(\n    max(abs(section_check[, 1] - fixed_nonzero)) < 1e-12,\n    max(abs(\n      rowSums(\n        (section_check %*% previous_precision) * section_check\n      ) - 1\n    )) < 1e-10\n  )\n\n  ellipsoid_rail <- function(angle, from, to, n = 241) {\n    first <- seq(from, to, length.out = n)\n    radius <- sqrt(1 - first^2)\n    sphere_rail <- cbind(\n      first,\n      radius * cos(angle),\n      radius * sin(angle)\n    )\n    sphere_rail %*% previous_cholesky\n  }\n\n  with_panel <- function(data, panel, group = NULL) {\n    data$panel <- factor(panel, levels = panel_levels)\n    if (!is.null(group)) {\n      data$group <- paste(panel, group, sep = \"::\")\n    }\n    data\n  }\n\n  # Common ellipsoid silhouette.\n  surface_grid <- expand.grid(\n    first = seq(-0.999, 0.999, length.out = 61),\n    angle = seq(0, 2 * pi, length.out = 121)\n  )\n  surface_radius <- sqrt(1 - surface_grid$first^2)\n  surface_sphere <- cbind(\n    surface_grid$first,\n    surface_radius * cos(surface_grid$angle),\n    surface_radius * sin(surface_grid$angle)\n  )\n  surface_projection <- project_3d(\n    surface_sphere %*% previous_cholesky\n  )\n  silhouette_one <- surface_projection[\n    chull(surface_projection$x, surface_projection$y),\n  ]\n  silhouette <- do.call(rbind, lapply(panel_levels, function(panel) {\n    with_panel(silhouette_one, panel, \"ellipsoid\")\n  }))\n\n  # Sparse common wireframe.\n  wire_parts <- list()\n  wire_id <- 1\n  for (value in seq(-0.8, 0.8, by = 0.2)) {\n    wire_parts[[wire_id]] <- cbind(\n      project_3d(ellipsoid_section(value)),\n      wire_group = paste0(\"ring\", wire_id)\n    )\n    wire_id <- wire_id + 1\n  }\n  for (angle in seq(0, 330, by = 30) * pi / 180) {\n    wire_parts[[wire_id]] <- cbind(\n      project_3d(ellipsoid_rail(angle, -0.999, 0.999)),\n      wire_group = paste0(\"rail\", wire_id)\n    )\n    wire_id <- wire_id + 1\n  }\n  wire_one <- do.call(rbind, wire_parts)\n  ellipsoid_wire <- do.call(rbind, lapply(panel_levels, function(panel) {\n    with_panel(wire_one, panel, wire_one$wire_group)\n  }))\n\n  zero_slice <- with_panel(\n    project_3d(ellipsoid_section(0)),\n    zero_panel,\n    \"zero\"\n  )\n  nonzero_slice <- with_panel(\n    project_3d(ellipsoid_section(fixed_nonzero)),\n    nonzero_panel,\n    \"nonzero\"\n  )\n\n  # The interval intersection: a projected silhouette, internal sections,\n  # curved boundary rails, and the two planar endpoint faces.\n  volume_grid <- expand.grid(\n    first = seq(lower_bound, upper_bound, length.out = 81),\n    angle = seq(0, 2 * pi, length.out = 181)\n  )\n  volume_radius <- sqrt(1 - volume_grid$first^2)\n  volume_sphere <- cbind(\n    volume_grid$first,\n    volume_radius * cos(volume_grid$angle),\n    volume_radius * sin(volume_grid$angle)\n  )\n  volume_projection <- project_3d(\n    volume_sphere %*% previous_cholesky\n  )\n  volume_silhouette <- with_panel(\n    volume_projection[\n      chull(volume_projection$x, volume_projection$y),\n    ],\n    bound_panel,\n    \"volume\"\n  )\n\n  internal_values <- seq(\n    lower_bound,\n    upper_bound,\n    length.out = 7\n  )[2:6]\n  bound_sections <- do.call(rbind, lapply(\n    seq_along(internal_values),\n    function(index) {\n      with_panel(\n        project_3d(ellipsoid_section(internal_values[index])),\n        bound_panel,\n        paste0(\"section\", index)\n      )\n    }\n  ))\n  bound_rails <- do.call(rbind, lapply(\n    seq_along(seq(0, 330, by = 30)),\n    function(index) {\n      angle <- seq(0, 330, by = 30)[index] * pi / 180\n      with_panel(\n        project_3d(ellipsoid_rail(\n          angle,\n          lower_bound,\n          upper_bound\n        )),\n        bound_panel,\n        paste0(\"bound_rail\", index)\n      )\n    }\n  ))\n  bound_faces <- rbind(\n    with_panel(\n      project_3d(ellipsoid_section(lower_bound)),\n      bound_panel,\n      \"lower_face\"\n    ),\n    with_panel(\n      project_3d(ellipsoid_section(upper_bound)),\n      bound_panel,\n      \"upper_face\"\n    )\n  )\n\n  # A common c1 axis and origin make central versus affine obvious.\n  c1_axis_3d <- rbind(c(-1.08, 0, 0), c(1.08, 0, 0))\n  c1_axis_projected <- project_3d(c1_axis_3d)\n  c1_axis <- do.call(rbind, lapply(panel_levels, function(panel) {\n    data.frame(\n      x = c1_axis_projected$x[1],\n      y = c1_axis_projected$y[1],\n      xend = c1_axis_projected$x[2],\n      yend = c1_axis_projected$y[2],\n      panel = factor(panel, levels = panel_levels)\n    )\n  }))\n  c1_label <- do.call(rbind, lapply(panel_levels, function(panel) {\n    data.frame(\n      x = c1_axis_projected$x[2],\n      y = c1_axis_projected$y[2],\n      label = \"c[1]\",\n      panel = factor(panel, levels = panel_levels)\n    )\n  }))\n  origin_projection <- project_3d(matrix(c(0, 0, 0), nrow = 1))\n  origins <- data.frame(\n    x = origin_projection$x,\n    y = origin_projection$y,\n    panel = factor(panel_levels, levels = panel_levels)\n  )\n  origin_labels <- transform(\n    origins,\n    x = x + 0.05,\n    y = y + 0.055,\n    label = \"0\"\n  )\n\n  nonzero_center_3d <- c(\n    fixed_nonzero,\n    0.5 * fixed_nonzero,\n    0.5 * fixed_nonzero\n  )\n  nonzero_center <- project_3d(matrix(nonzero_center_3d, nrow = 1))\n  offset_segment <- data.frame(\n    x = origin_projection$x,\n    y = origin_projection$y,\n    xend = nonzero_center$x,\n    yend = nonzero_center$y,\n    panel = factor(nonzero_panel, levels = panel_levels)\n  )\n\n  # In Cholesky coordinates, fixing the first coordinate to q leaves\n  # v_2^2 + v_3^2 < 1 - q^2. Draw one transformed radius in each\n  # section so the spent and remaining parts of that budget are visible.\n  free_radius_segment <- function(value, panel) {\n    radius <- sqrt(1 - value^2)\n    points <- rbind(\n      c(value, 0, 0),\n      c(value, 0, radius)\n    ) %*% previous_cholesky\n    projected <- project_3d(points)\n    data.frame(\n      x = projected$x[1],\n      y = projected$y[1],\n      xend = projected$x[2],\n      yend = projected$y[2],\n      panel = factor(panel, levels = panel_levels)\n    )\n  }\n\n  zero_radius_segment <- free_radius_segment(0, zero_panel)\n  bound_radius_segments <- rbind(\n    transform(\n      free_radius_segment(lower_bound, bound_panel),\n      face = \"lower\"\n    ),\n    transform(\n      free_radius_segment(upper_bound, bound_panel),\n      face = \"upper\"\n    )\n  )\n  nonzero_radius_segment <- free_radius_segment(\n    fixed_nonzero,\n    nonzero_panel\n  )\n\n  radius_target <- function(segment, fraction = 0.62) {\n    c(\n      x = segment$x + fraction * (segment$xend - segment$x),\n      y = segment$y + fraction * (segment$yend - segment$y)\n    )\n  }\n  callout_targets <- rbind(\n    radius_target(zero_radius_segment),\n    radius_target(subset(bound_radius_segments, face == \"lower\")),\n    radius_target(subset(bound_radius_segments, face == \"upper\")),\n    radius_target(nonzero_radius_segment)\n  )\n  free_radius_arrows <- data.frame(\n    arrow_x = c(0.40, -0.10, -0.26, -0.37),\n    arrow_y = rep(0.84, 4),\n    xend = callout_targets[, \"x\"],\n    yend = callout_targets[, \"y\"],\n    constraint = factor(\n      c(\"zero\", \"bound\", \"bound\", \"nonzero\"),\n      levels = c(\"zero\", \"bound\", \"nonzero\")\n    ),\n    panel = factor(\n      c(zero_panel, bound_panel, bound_panel, nonzero_panel),\n      levels = panel_levels\n    )\n  )\n  free_radius_labels <- data.frame(\n    label_x = c(0.40, -0.18, -0.37),\n    label_y = rep(0.91, 3),\n    constraint = factor(\n      c(\"zero\", \"bound\", \"nonzero\"),\n      levels = c(\"zero\", \"bound\", \"nonzero\")\n    ),\n    panel = factor(panel_levels, levels = panel_levels),\n    label = \"free radius\"\n  )\n\n  ggplot() +\n    geom_polygon(\n      data = silhouette,\n      aes(x, y, group = group),\n      fill = blog_colors$blue,\n      color = NA,\n      alpha = 0.055\n    ) +\n    geom_path(\n      data = ellipsoid_wire,\n      aes(x, y, group = group),\n      color = blog_colors$blue,\n      alpha = 0.07,\n      linewidth = 0.35\n    ) +\n    geom_segment(\n      data = c1_axis,\n      aes(x = x, y = y, xend = xend, yend = yend),\n      color = blog_colors$text_light,\n      linetype = \"22\",\n      linewidth = 0.55,\n      arrow = grid::arrow(\n        length = grid::unit(0.10, \"cm\"),\n        type = \"closed\"\n      )\n    ) +\n    geom_polygon(\n      data = volume_silhouette,\n      aes(x, y, group = group),\n      fill = blog_colors$teal,\n      color = NA,\n      alpha = 0.045\n    ) +\n    geom_path(\n      data = bound_sections,\n      aes(x, y, group = group),\n      color = blog_colors$teal,\n      alpha = 0.24,\n      linewidth = 0.35\n    ) +\n    geom_path(\n      data = bound_rails,\n      aes(x, y, group = group),\n      color = blog_colors$teal,\n      alpha = 0.48,\n      linewidth = 0.45\n    ) +\n    geom_polygon(\n      data = subset(bound_faces, grepl(\"lower_face\", group)),\n      aes(x, y, group = group),\n      fill = blog_colors$teal,\n      color = blog_colors$teal,\n      alpha = 0.06,\n      linetype = \"22\",\n      linewidth = 0.9\n    ) +\n    geom_polygon(\n      data = subset(bound_faces, grepl(\"upper_face\", group)),\n      aes(x, y, group = group),\n      fill = blog_colors$teal,\n      color = blog_colors$teal,\n      alpha = 0.16,\n      linewidth = 1.05\n    ) +\n    geom_polygon(\n      data = zero_slice,\n      aes(x, y, group = group),\n      fill = blog_colors$purple,\n      color = blog_colors$purple,\n      alpha = 0.27,\n      linewidth = 1.2\n    ) +\n    geom_polygon(\n      data = nonzero_slice,\n      aes(x, y, group = group),\n      fill = blog_colors$gold,\n      color = blog_colors$gold,\n      alpha = 0.27,\n      linewidth = 1.2\n    ) +\n    geom_path(\n      data = ellipsoid_wire,\n      aes(x, y, group = group),\n      color = blog_colors$blue,\n      alpha = 0.23,\n      linewidth = 0.30\n    ) +\n    geom_segment(\n      data = zero_radius_segment,\n      aes(x = x, y = y, xend = xend, yend = yend),\n      color = blog_colors$purple,\n      linewidth = 1.05,\n      arrow = grid::arrow(\n        length = grid::unit(0.10, \"cm\"),\n        type = \"closed\"\n      )\n    ) +\n    geom_segment(\n      data = bound_radius_segments,\n      aes(x = x, y = y, xend = xend, yend = yend),\n      color = blog_colors$teal,\n      linewidth = 1.05,\n      arrow = grid::arrow(\n        length = grid::unit(0.10, \"cm\"),\n        type = \"closed\"\n      )\n    ) +\n    geom_segment(\n      data = offset_segment,\n      aes(x = x, y = y, xend = xend, yend = yend),\n      color = blog_colors$gold,\n      linetype = \"22\",\n      linewidth = 0.95,\n      arrow = grid::arrow(\n        length = grid::unit(0.10, \"cm\"),\n        type = \"closed\"\n      )\n    ) +\n    geom_segment(\n      data = nonzero_radius_segment,\n      aes(x = x, y = y, xend = xend, yend = yend),\n      color = blog_colors$gold,\n      linewidth = 1.05,\n      arrow = grid::arrow(\n        length = grid::unit(0.10, \"cm\"),\n        type = \"closed\"\n      )\n    ) +\n    geom_point(\n      data = origins,\n      aes(x, y),\n      shape = 21,\n      fill = blog_colors$background,\n      color = blog_colors$navy,\n      size = 2.6,\n      stroke = 0.9\n    ) +\n    geom_text(\n      data = origin_labels,\n      aes(x, y, label = label),\n      color = blog_colors$navy,\n      size = 3.0,\n      hjust = 0,\n      vjust = 0\n    ) +\n    geom_point(\n      data = transform(\n        nonzero_center,\n        panel = factor(nonzero_panel, levels = panel_levels)\n      ),\n      aes(x, y),\n      color = blog_colors$gold,\n      size = 2.4\n    ) +\n    geom_curve(\n      data = free_radius_arrows,\n      aes(\n        x = arrow_x,\n        y = arrow_y,\n        xend = xend,\n        yend = yend,\n        color = constraint\n      ),\n      curvature = 0.10,\n      linewidth = 0.65,\n      arrow = grid::arrow(\n        length = grid::unit(0.10, \"cm\"),\n        type = \"closed\"\n      )\n    ) +\n    geom_text(\n      data = free_radius_labels,\n      aes(\n        x = label_x,\n        y = label_y,\n        label = label,\n        color = constraint\n      ),\n      fontface = \"bold\",\n      size = 3.0\n    ) +\n    geom_text(\n      data = c1_label,\n      aes(x, y, label = label),\n      parse = TRUE,\n      color = blog_colors$text_light,\n      hjust = 1.1,\n      vjust = 1.1,\n      size = 3.3\n    ) +\n    scale_color_manual(\n      values = c(\n        zero = blog_colors$purple,\n        bound = blog_colors$teal,\n        nonzero = blog_colors$gold\n      ),\n      guide = \"none\"\n    ) +\n    facet_wrap(~panel, nrow = 1) +\n    coord_equal(\n      xlim = c(-1.35, 1.35),\n      ylim = c(-1.20, 1.25),\n      expand = FALSE\n    ) +\n    theme_blog() +\n    theme(\n      panel.grid = element_blank(),\n      panel.grid.major = element_blank(),\n      panel.grid.minor = element_blank(),\n      axis.title = element_blank(),\n      axis.text = element_blank(),\n      axis.ticks = element_blank(),\n      axis.line = element_blank(),\n      legend.position = \"none\",\n      strip.text = element_text(size = 9.6, lineheight = 1.12)\n    ) +\n    labs(\n      title = \"Zero, Bound, and Nonzero Constraints Use the Row Budget Differently\",\n      subtitle = paste(\n        \"Cholesky-row budget:  q² + free² < 1.\",\n        \"Fixing q leaves radius √(1 − q²); an interval makes that radius vary.\"\n      )\n    )\n})\n\nschur_constraint_plot\n```\n\n::: {.cell-output-display}\n![All three panels fix the leading $3\\times3$ block $R$ and vary $c=(\\Omega_{4,1},\\Omega_{4,2},\\Omega_{4,3})$. In this example the first Cholesky-row coordinate equals $c_1=q$, so positive definiteness requires $q^2+v_2^2+v_3^2<1$. The colored spokes show the image of the remaining Cholesky radius $\\sqrt{1-q^2}$: it is $1$ at zero, falls from $0.84$ to $0.53$ across the bounded interval, and is $0.71$ at the exact value $q=0.70$. Thus zero is a homogeneous section through the full radius, the bound retains three-dimensional volume but gives every section a different budget, and the nonzero equality is an affine section with $0.49$ of the squared-norm budget already fixed. With several fixed values, the fixed share is generally $\\kappa=q^{\\mathsf T}G^{-1}q$ and the remaining radius is $\\sqrt{1-\\kappa}$; it can shrink to tangency or become infeasible. The ordinary-correlation intersections remain convex, so the difficulty is a completion boundary rather than disconnected target regions. Look-ahead propagates $[0,0]$, $[\\ell,u]$, and $[q,q]$ through the same local $3\\times3$ projection.](corr-bounds_files/figure-html/fig-schur-ellipsoid-slabs-1.png){#fig-schur-ellipsoid-slabs width=1152}\n:::\n:::\n\n\n## 3. The Smooth Triangular Sign Transform\n\nSign constraints retain one useful property: they are homogeneous. If $c$ has the right signs, then $a c$ has the same signs for every $a>0$. Their directions form an orthant cone; the Schur ellipsoid truncates each ray at the positive-definite boundary.\n\nLet $s_j\\in\\{-1,+1\\}$ be the requested sign of correlation $(i,j)$. Choose a smooth, strictly increasing bijection $g:\\mathbb R\\to(0,\\infty)$ with $g'(y)>0$, and set\n\n$$x_j=s_j\\,g(y_j), \\qquad g(y)>0.$$\n\nThe implementation uses the numerically stable softplus divided by $2K$, which has these properties. The factor $2K$ changes the scale near the default initialization but not the image $(0,\\infty)$. Solve through the previous Cholesky triangle,\n\n$$w=B^{-1}x, \\qquad t=w'w,$$\n\nthen reuse the modified stereographic hemisphere map from @pinkney2025,\n\n$$a(t)=\\frac{\\sqrt{t+2}}{t+1}, \\qquad\nv=a(t)w, \\qquad\nL_{ii}=\\frac{1}{t+1}.$$\n\nThe row has unit norm because\n\n$$v'v+L_{ii}^2\n=\\frac{t(t+2)+1}{(t+1)^2}=1.$$\n\nThe corresponding ordinary correlations are\n\n$$c=Bv=a(t)Bw=a(t)x.$$\n\nSince $a(t)>0$, every correlation has exactly the requested sign. In exact arithmetic, every finite raw vector therefore produces a positive-definite correlation matrix in the desired orthant without a feasibility check, projection, or rejection.\n\nTo check coverage conditional on the previous rows, take any $c$ with the prescribed strict signs and $q=c'(BB')^{-1}c<1$. Set $v=B^{-1}c$. The inverse radial coordinate is unique:\n\n$$t=\\frac{1}{\\sqrt{1-q}}-1.$$\n\nThen $w=v/a(t)$ and $x=Bw=c/a(t)$. Because $a(t)>0$, $x$ has the same signs as $c$, and $g$ can be inverted coordinate by coordinate. Thus each admissible row has one finite raw preimage. Applying this inverse successively from row 2 through row $K$ establishes the bijection for the complete matrix.\n\n### 3.1 Jacobian\n\nAt fixed earlier rows, the determinants from $x\\mapsto w=B^{-1}x$ and $v\\mapsto c=Bv$ cancel. For $d=i-1$, the row contribution with respect to the ordinary correlations is\n\n$$\\det\\left\\{\\frac{\\partial(a(t)w)}{\\partial w}\\right\\}\n=a(t)^d\\left\\{1+2t\\frac{a'(t)}{a(t)}\\right\\}\n=\\frac{2(t+2)^{(d-2)/2}}{(1+t)^{d+1}},$$\n\nwhere the first equality follows from the matrix determinant lemma. Including the coordinate-wise derivative of $g$ gives\n\n$$\\log J_i\n=\\sum_{j=1}^{d}\\log g'(y_j)\n +\\log 2\n +\\frac{d-2}{2}\\log(t+2)\n -(d+1)\\log(1+t).$$\n\nThe complete raw-to-free-correlation Jacobian is block triangular by rows, so the full log Jacobian is $\\sum_i\\log J_i$. The Stan target is then\n\n$$\\log J+(\\eta-1)\\log\\det(\\Omega).$$\n\nThis ordinary-correlation formulation matters. Using `lkj_corr_cholesky_lpdf` would instead require the raw-to-free-Cholesky Jacobian; combining that density with the ordinary-correlation Jacobian above would count the Cholesky-to-correlation change of variables twice.\n\nAny strict sign pattern is nonempty. Let $S$ be the symmetric zero-diagonal matrix whose off-diagonal entries are the requested signs. Then $I+\\epsilon S$ has that pattern and is positive definite whenever $0<\\epsilon<1/\\lVert S\\rVert_2$. For an all-negative matrix, $\\mathbf 1'\\Omega\\mathbf 1>0$ also places the mean off-diagonal correlation in $(-1/(K-1),0)$. Equivalently, its mean absolute correlation is less than $1/(K-1)$.\n\n## 4. A Feasible Anchor for the Global-Ray Construction {#sec-global-ray}\n\nIndividually sensible intervals need not admit a correlation matrix. For example, at $K=3$ the bounds\n\n$$\\Omega_{12},\\Omega_{13}\\in[0.8,0.9],\\qquad\n\\Omega_{23}\\in[-0.9,-0.8]$$\n\nare infeasible. Writing these entries as $a$, $b$, and $c$, respectively, gives\n\n$$\\det(\\Omega)=1+2abc-a^2-b^2-c^2\n\\le 1-1.024-1.92=-1.944.$$\n\nThis example shows why a general-box construction needs a separate feasibility check.\n\nFor now, suppose every interval has positive width. Let $\\Omega_0$ be a strictly feasible anchor: it is positive definite and every off-diagonal entry lies strictly between its bounds. Vectorize the $D=K(K-1)/2$ lower-triangular entries, choose a unit direction $u\\in\\mathbb S^{D-1}$, and place it into a symmetric zero-diagonal matrix $U(u)$.\n\nAlong the ray\n\n$$\\Omega(r)=\\Omega_0+rU,$$\n\neach box face supplies an upper limit on $r$. If $U_{ij}>0$, that limit is $(u_{ij}-\\Omega_{0,ij})/U_{ij}$; if $U_{ij}<0$, it is $(\\ell_{ij}-\\Omega_{0,ij})/U_{ij}$. Let their minimum be $R_{\\text{box}}(u)$.\n\nThe positive-definite boundary is also available exactly. With $\\Omega_0=L_0L_0'$ and\n\n$$A(u)=L_0^{-1}U(u)L_0^{-T},$$\n\nwe have\n\n$$\\Omega_0+rU=L_0\\{I+rA(u)\\}L_0'.$$\n\nBecause $U$ is nonzero, symmetric, and has trace zero, it has both positive and negative eigenvalues. Moreover, $A(u)=S U(u)S'$ with the nonsingular matrix $S=L_0^{-1}$, so $A(u)$ and $U(u)$ have the same inertia by Sylvester's law of inertia [@sylvester1852; @hornJohnson2013, Theorem 4.5.8, p. 282]. Hence $\\lambda_{\\min}\\{A(u)\\}<0$, and the first positive ray intersection with the semidefinite boundary is\n\n$$R_{\\text{PD}}(u)=-\\frac{1}{\\lambda_{\\min}\\{A(u)\\}}.$$\n\nSet $R(u)=\\min\\{R_{\\text{box}}(u),R_{\\text{PD}}(u)\\}$ and\n\n$$\\Omega=\\Omega_0+\\rho R(u)U(u),\\qquad 0<\\rho<1.$$\n\nThe intersection of the box, the affine unit-diagonal space, and the positive-definite cone is convex, so it is star-shaped about $\\Omega_0$. Conversely, any point in its interior other than $\\Omega_0$ determines a unique direction\n\n$$u=\\frac{\\operatorname{vech}_{\\!\\ell}(\\Omega-\\Omega_0)}\n{\\lVert\\operatorname{vech}_{\\!\\ell}(\\Omega-\\Omega_0)\\rVert}$$\n\nand a unique $\\rho=\\lVert\\operatorname{vech}_{\\!\\ell}(\\Omega-\\Omega_0)\\rVert/R(u)$. Thus $(\\rho,u)\\mapsto\\Omega$ is one-to-one and onto the feasible interior except for the anchor, a single omitted point. The normalized $z$ representation adds an auxiliary radius, handled below, rather than another correlation-matrix coordinate.\n\n### 4.1 Jacobian and the Auxiliary Direction\n\nLet $h=\\operatorname{vech}_{\\!\\ell}(\\Omega-\\Omega_0)$ and let $d\\sigma(u)$ denote surface measure on $\\mathbb S^{D-1}$. Polar volume gives\n\n$$dh=\\rho^{D-1}R(u)^D\\,d\\rho\\,d\\sigma(u).$$\n\nAngular derivatives of $R(u)$ do not add another term. In local angular coordinates, the part involving $\\partial R/\\partial\\theta$ is proportional to $u$, so it is collinear with the radial derivative and drops out of the determinant. The implementation obtains a uniform direction as $u=z/\\lVert z\\rVert$ with $z\\sim\\mathcal N(0,I_D)$. Under the isotropic normal density, $u$ is uniform on the sphere and independent of the chi-distributed norm of $z$. Without that radial density, the target would be improper along rescalings of $z$.\n\nIn exact arithmetic, a strict anchor makes every finite raw state feasible, but the map is not globally smooth. The minimum changes identity where two box faces exchange roles or where the active boundary changes between a box face and the positive-definite cone. Differentiability can also fail when the smallest eigenvalue has multiplicity greater than one. The boundary-radius function is differentiable almost everywhere; ties and eigenvalue multiplicities are possible exceptions. They do not change the almost-everywhere Jacobian used for the continuous target, although an HMC trajectory can cross the resulting kinks. The auxiliary direction must be initialized away from zero. The supplied Stan implementation requires $K\\ge3$ and at least two free correlations; the one-dimensional case should instead use a direct scalar transform over its feasible interval.\n\n## 5. Exact Nonzero Correlations Are Affine Slices\n\nSuppose selected correlations are fixed exactly rather than merely bounded. In row $i$, let the nonempty set $Z$ index the fixed correlations, let $q$ contain their specified values, and let $P_Z$ select those cells from $c=Bv$. Rows with $Z=\\varnothing$ use the unconstrained row map. For $Z\\ne\\varnothing$, the row constraint is\n\n$$Av=q,\\qquad A=P_ZB.$$\n\nFor a structural zero, $q=0$ and the solution set is the linear null space used by `tri`. For $q\\ne0$, the solution set is an affine translation that does not pass through the origin. This translation uses part of the available Cholesky row norm, so substituting a nonzero right-hand side into the zero basis while leaving the rest of the transform unchanged is not sufficient.\n\nLet\n\n$$G=AA'=\\Omega_{Z,Z},\\qquad\nv_0=A'G^{-1}q,$$\n\nso that $v_0$ is the minimum-norm particular solution, and let $Q$ be an orthonormal basis for $\\ker(A)$. Then $Q'v_0=0$ and every solution is $v=v_0+Qz$. A positive diagonal remains available exactly when\n\n$$\\kappa=q'G^{-1}q<1.$$\n\nIndeed, $v_0'v_0=\\kappa$ and $v'v=\\kappa+z'z$, so the remaining squared row radius is $1-\\kappa$.\n\nWriting $r_0=\\sqrt{1-\\kappa}$, $d=i-1-|Z|$, $t=y'y$, and\n\n$$u(y)=\\frac{\\sqrt{t+2}}{t+1}y,$$\n\nthe affine row transform is\n\n$$v=v_0+r_0Qu(y),\\qquad L_{ii}=\\frac{r_0}{t+1}.$$\n\nIt enforces $Av=q$ and satisfies $v'v+L_{ii}^2=1$. Because $u(y)$ is a bijection from $\\mathbb R^d$ to the open unit ball, this transform covers the current-row completions whenever $\\kappa<1$. With $B_F=P_FB$, its row log Jacobian with respect to the remaining ordinary correlations $c_F$ is\n\n$$\\log J_i\n=\\log J_{\\text{stereo}}(y)+d\\log r_0\n +\\log\\left|\\det(B_FQ)\\right|,$$\n\nwhere\n\n$$\\log J_{\\text{stereo}}(y)\n=\\log 2+\\frac{d-2}{2}\\log(t+2)-(d+1)\\log(1+t).$$\n\nThe remaining determinant follows by forming the orthogonal matrix\n\n$$O=\\left[Q,\\ A'G^{-1/2}\\right].$$\n\nAfter permuting the rows into $F,Z$ order, $BO$ is block upper triangular with diagonal blocks $B_FQ$ and $G^{1/2}$. Hence\n\n$$|\\det(B_FQ)|=\\frac{\\det(B)}{\\sqrt{\\det(G)}}.$$\n\nThe $d\\log r_0$ term comes from scaling $d$ free coordinates by $r_0$. It vanishes in the zero case because then $v_0=0$ and $r_0=1$. If $d=0$, the row has no free parameter and its empty-coordinate Jacobian is one.\n\nThis gives a transform for the *current* row whenever $\\kappa<1$, but not a global completion guarantee. At $K=3$, fix\n\n$$\\Omega_{31}=0.8,\\qquad \\Omega_{32}=-0.8,$$\n\nand call the earlier free correlation $r=\\Omega_{21}$. Positive definiteness requires\n\n$$1+2r(0.8)(-0.8)-r^2-0.8^2-(-0.8)^2>0,$$\n\nwhich reduces to $-1<r<-0.28$. An earlier draw such as $r=0.5$ is a valid $2\\times2$ correlation matrix and would be allowed by a broad cell bound such as $(-1,1)$, but it leaves no possible third row. This prefix failure does not occur with zero equalities alone because $v=0$ is always a feasible row interior. A nonzero affine row retains a positive radius under additional structure—for example, if $G$ is fixed and the specified block\n\n$$\\begin{pmatrix}G&q\\\\q'&1\\end{pmatrix}$$\n\nis positive definite, then its Schur complement gives $q'G^{-1}q<1$.\n\nThe global construction avoids these prefix dead ends. Let $H$ denote all fixed cells, $F$ the $D_F$ remaining cells, and choose an anchor $\\Omega_0$ that is strictly positive definite, satisfies $\\Omega_{0,H}=q_H$ exactly, and lies strictly inside every free-cell bound. Draw directions only in the free coordinates and embed them as a symmetric matrix $U$ with\n\n$$U_H=0.$$\n\nThe box and positive-definite ray limits from @sec-global-ray are otherwise unchanged. Consequently,\n\n$$\\Omega=\\Omega_0+\\rho R(U)U$$\n\nholds every specified correlation fixed for every raw input. Because the intersection of the positive-definite cone, the free-cell box, and the affine fixed-value space is convex, the same unique-ray argument shows that the reduced map covers its relative interior in the free-coordinate affine subspace, apart from the anchor. Its polar Jacobian is\n\n$$\\rho^{D_F-1}R(U)^{D_F}$$\n\nwith respect to the $D_F$ free ordinary correlations. There is no additional triangular Gram or delta term: the fixed coordinates have already been removed from the base measure.\n\nThe supplied global-ray Stan program implements this reduction. A fixed cell is encoded by setting its lower and upper bounds equal and including it in `N_fixed`; the anchor must match the value exactly. Prefer constructing or optimizing the anchor subject to those equalities. If fixed values are copied into an existing candidate, recheck positive definiteness and the strict margins for every free bound. The normalized-direction implementation requires at least two remaining free cells. With one free correlation, use a scalar logistic over its exact feasible interval; with none, the matrix is fixed data and only needs validation.\n\n### 5.1 Numerical Check Against IID Rejection\n\n\n\nAs a check, I fixed $\\Omega_{31}=0.55$ and $\\Omega_{42}=-0.35$ in a $K=4$, $\\eta=2$ matrix and gave the other four correlations heterogeneous finite bounds. Thirteen of the box's sixteen corners are not positive definite, and the positive-definite boundary supplied the active ray limit for 18.4% of the retained draws.\n\nFor an independent reference, I drew 500,000 points uniformly from the four-dimensional free box. Because $\\eta=2$, the target kernel is $\\det(\\Omega)$; Hadamard's inequality gives $0<\\det(\\Omega)\\le1$ for a positive-definite correlation matrix. Retaining positive-definite proposals with probability $\\det(\\Omega)$ therefore produced 108,553 IID draws from the same LKJ slice. The Stan fit retained 6,000 draws. No fixed-cell or bound violation was recorded, the smallest sampled eigenvalue was 0.010, and there were 0 divergences.\n\n\n::: {#tbl-fixed-values-validation .cell tbl-cap='Reduced global-ray samples compared with an IID rejection reference for two exact nonzero correlations.'}\n\n```{.r .cell-code}\nfixed_comparison |>\n  transmute(\n    Correlation = variable,\n    `Stan mean` = round(stan_mean, 3),\n    `IID mean` = round(reference_mean, 3),\n    `Mean difference` = round(mean_difference, 3),\n    `Largest quantile difference` = round(max_quantile_difference, 3)\n  ) |>\n  knitr::kable(align = c(\"l\", rep(\"r\", 4)))\n```\n\n::: {.cell-output-display}\n\n\n|Correlation | Stan mean| IID mean| Mean difference| Largest quantile difference|\n|:-----------|---------:|--------:|---------------:|---------------------------:|\n|Omega[2,1]  |    -0.077|   -0.068|          -0.009|                       0.011|\n|Omega[3,2]  |    -0.007|   -0.002|          -0.005|                       0.011|\n|Omega[4,1]  |     0.060|    0.051|           0.009|                       0.013|\n|Omega[4,3]  |     0.086|    0.075|           0.012|                       0.019|\n\n\n:::\n:::\n\n\nThe largest absolute mean difference was 0.012, or 2.09 combined Monte Carlo standard errors. The largest difference among the 5th, 50th, and 95th percentiles was 0.019. This agreement is a numerical check of the reduced-coordinate implementation, including its Jacobian; it is not a proof. It also does not compare the sampling efficiency of the ray and triangular geometries.\n\n## 6. A Direct Logistic Transform for Certified Boxes\n\nFor one heterogeneous example, I constructed a box certified to lie wholly inside the elliptope. Let $\\Omega_0$ be positive definite and write any matrix in the box as $\\Omega_0+E$. Define\n\n$$m_{ij}=\\max\\{|\\ell_{ij}-\\Omega_{0,ij}|,\n|u_{ij}-\\Omega_{0,ij}|\\}.$$\n\nIf\n\n$$\\max_i\\sum_{j\\ne i}m_{ij}<\\lambda_{\\min}(\\Omega_0),$$\n\nthen\n\n$$\\lambda_{\\min}(\\Omega_0+E)\n\\ge \\lambda_{\\min}(\\Omega_0)-\\lVert E\\rVert_2\n\\ge \\lambda_{\\min}(\\Omega_0)-\\lVert E\\rVert_\\infty>0.$$\n\nThe second inequality uses symmetry: $\\lVert E\\rVert_2\\le\n\\sqrt{\\lVert E\\rVert_1\\lVert E\\rVert_\\infty}\n=\\lVert E\\rVert_\\infty$, and $\\lVert E\\rVert_\\infty\\le\\max_i\\sum_{j\\ne i}m_{ij}$.\n\nEvery point in that box is therefore positive definite, and independent lower/upper logistic transforms are sufficient. This certificate is conservative: it covers only a subset of feasible boxes, but applies when bounds are generated around a known matrix or are scientifically narrow.\n\nFor arbitrary user-supplied boxes, finding a strict anchor can be written as the semidefinite program\n\n$$\\begin{aligned}\n\\operatorname*{maximize}_{\\Omega_0,\\delta}\\quad &\\delta\\\\\n\\text{subject to}\\quad\n&\\Omega_0\\succeq\\delta I,\\qquad \\operatorname{diag}(\\Omega_0)=\\mathbf 1,\\\\\n&\\ell_{ij}+\\delta\\le\\Omega_{0,ij}\\le u_{ij}-\\delta.\n\\end{aligned}$$\n\nA solution with $\\delta>0$ supplies the required anchor. Conversely, any strict anchor makes some positive $\\delta$ feasible, so for the exact program, $\\delta^\\star>0$ is equivalent to the existence of an anchor with both positive spectral margin and strict free-bound margins. A numerical optimum near zero still has to be interpreted using the solver's feasibility residuals and tolerances. Endpoints lying in $[-1,1]$ alone do not establish joint feasibility. For fixed cells, replace the corresponding two inequalities by equalities and omit those cells from the bound-margin constraint.\n\n## 7. Sampling Experiments\n\nI tested five $K=5$, $\\eta=2$ prior-only cases in Stan [@carpenter2017]:\n\n| scenario | constraints | transforms compared |\n|:-----------------------|:-----------------------|:-----------------------|\n| all positive | every $\\Omega_{ij}\\in(0,1)$ | triangular sign, global ray |\n| all negative | every $\\Omega_{ij}\\in(-1,0)$ | triangular sign, global ray |\n| mixed signs | random positive/negative sign per cell | triangular sign, global ray |\n| certified heterogeneous box | random asymmetric intervals wholly inside the elliptope | certified direct box, global ray |\n| wide heterogeneous box | random asymmetric intervals with non-PD corners | global ray |\n\nEach fit used four chains, 750 warmup iterations, 1,500 retained iterations, `adapt_delta = 0.90`, and `max_treedepth = 12`. The certified heterogeneous widths were scaled until the spectral bound in Section 6 gave a minimum eigenvalue of at least 0.22 throughout the box. The wide box has a strict feasible anchor but a minimum corner eigenvalue of -1.10; independent logits over its cells would therefore map some raw states to non-positive-definite matrices. Wall-clock times below describe this run and are not intended as portable hardware comparisons.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(tidyr)\n\nsource(\"../../R/theme_blog.R\")\n\ndiagnostics <- read.csv(\"bounds-diagnostics.csv\")\ncells <- read.csv(\"bounds-cell-summary.csv\")\nselected <- read.csv(\"bounds-selected-draws.csv\")\nbounds <- read.csv(\"bounds-scenarios.csv\")\nrun_settings <- read.csv(\"bounds-run-settings.csv\")\n\nscenario_labels <- c(\n  all_positive = \"All positive\",\n  all_negative = \"All negative\",\n  mixed_signs = \"Mixed signs\",\n  heterogeneous_box = \"Certified heterogeneous box\",\n  wide_heterogeneous_box = \"Wide heterogeneous box\"\n)\nmodel_labels <- c(\n  tri_sign = \"Triangular sign\",\n  global_ray = \"Global ray\",\n  direct_box = \"Certified direct box\"\n)\n\ndiagnostics <- diagnostics |>\n  mutate(\n    scenario_label = factor(scenario_labels[scenario],\n                            levels = unname(scenario_labels)),\n    model_label = factor(model_labels[model],\n                         levels = unname(model_labels))\n  )\ncells <- cells |>\n  mutate(\n    scenario_label = factor(scenario_labels[scenario],\n                            levels = unname(scenario_labels)),\n    model_label = factor(model_labels[model],\n                         levels = unname(model_labels))\n  )\nselected <- selected |>\n  mutate(\n    scenario_label = factor(scenario_labels[scenario],\n                            levels = unname(scenario_labels)),\n    model_label = factor(model_labels[model],\n                         levels = unname(model_labels))\n  )\n\nreference_cells <- cells |>\n  filter(model != \"global_ray\") |>\n  select(scenario, scenario_label, variable,\n         reference_model = model_label,\n         reference_mean = mean,\n         reference_mcse = mcse_mean,\n         reference_q05 = q05,\n         reference_q50 = q50,\n         reference_q95 = q95)\n\nparity <- cells |>\n  filter(model == \"global_ray\") |>\n  select(scenario, variable,\n         ray_mean = mean, ray_mcse = mcse_mean,\n         ray_q05 = q05, ray_q50 = q50, ray_q95 = q95) |>\n  inner_join(reference_cells, by = c(\"scenario\", \"variable\"))\n\nmax_mean_difference <- max(abs(parity$reference_mean - parity$ray_mean))\nmax_standardized_difference <- max(\n  abs(parity$reference_mean - parity$ray_mean)\n  / sqrt(parity$reference_mcse^2 + parity$ray_mcse^2)\n)\nmax_quantile_difference <- max(abs(c(\n  parity$reference_q05 - parity$ray_q05,\n  parity$reference_q50 - parity$ray_q50,\n  parity$reference_q95 - parity$ray_q95\n)))\n```\n:::\n\n\n### 7.1 The Bounds Used\n\nThe first three boxes impose signs only. The two heterogeneous boxes contain different lower and upper endpoints for all ten cells, including intervals that do not contain zero.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbounds |>\n  mutate(\n    scenario_label = factor(scenario_labels[scenario],\n                            levels = unname(scenario_labels)),\n    cell = sprintf(\"(%d,%d)\", row, col)\n  ) |>\n  ggplot(aes(y = cell)) +\n  geom_linerange(aes(xmin = lower, xmax = upper),\n                 linewidth = 1.1, color = blog_colors$teal) +\n  geom_point(aes(x = anchor), color = blog_colors$red, size = 2) +\n  facet_wrap(~scenario_label, scales = \"free_x\", ncol = 2) +\n  theme_blog() +\n  labs(x = \"Correlation\", y = \"Cell\",\n       title = \"Elementwise Bounds\",\n       subtitle = \"Red points are strict feasible anchors\")\n```\n\n::: {.cell-output-display}\n![Bounds and strict feasible anchors used in the five experiments. The certified heterogeneous intervals lie wholly inside the elliptope; the wide heterogeneous box has non-PD corners.](corr-bounds_files/figure-html/fig-scenario-bounds-1.png){#fig-scenario-bounds width=960}\n:::\n:::\n\n\n### 7.2 A Numerical Cross-Check\n\nThe derivations imply that the triangular sign map and global ray target the same bounded LKJ distribution in the first three scenarios. They likewise imply that the direct logistic and global ray have the same target for the certified heterogeneous box. The simulations provide a separate numerical check: across the 40 matched cell comparisons, the largest sample-mean difference is 0.010.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(parity, aes(x = reference_mean, y = ray_mean)) +\n  geom_abline(slope = 1, intercept = 0,\n              color = blog_colors$gold, linewidth = 0.9) +\n  geom_errorbar(aes(ymin = ray_mean - 2 * ray_mcse,\n                    ymax = ray_mean + 2 * ray_mcse),\n                width = 0, color = blog_colors$blue, alpha = 0.75) +\n  geom_errorbar(aes(xmin = reference_mean - 2 * reference_mcse,\n                    xmax = reference_mean + 2 * reference_mcse),\n                orientation = \"y\", width = 0,\n                color = blog_colors$blue, alpha = 0.75) +\n  geom_point(color = blog_colors$teal, size = 2) +\n  facet_wrap(~scenario_label) +\n  coord_equal() +\n  theme_blog() +\n  labs(x = \"Triangular sign or certified-box mean\",\n       y = \"Global-ray mean\",\n       title = \"Cellwise Mean Comparison\")\n```\n\n::: {.cell-output-display}\n![Sample means from independent parameterizations of the same bounded LKJ targets. Error bars are two Monte Carlo standard errors; the diagonal is the equality line.](corr-bounds_files/figure-html/fig-mean-parity-1.png){#fig-mean-parity width=960}\n:::\n:::\n\n\nThe largest difference is 2.50 combined Monte Carlo standard errors. Across the 5th, 50th, and 95th percentiles, the largest absolute quantile difference is 0.020. These are marginal implementation checks; they do not test the complete joint distribution or prove either Jacobian.\n\nThe next figure compares selected-cell marginals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(selected, aes(x = value, color = model_label, fill = model_label)) +\n  geom_density(alpha = 0.12, linewidth = 0.9, adjust = 1.4) +\n  facet_wrap(~scenario_label, scales = \"free\", ncol = 2) +\n  scale_color_manual(values = c(\n    \"Triangular sign\" = blog_colors$teal,\n    \"Global ray\" = blog_colors$purple,\n    \"Certified direct box\" = blog_colors$blue\n  )) +\n  scale_fill_manual(values = c(\n    \"Triangular sign\" = blog_colors$teal,\n    \"Global ray\" = blog_colors$purple,\n    \"Certified direct box\" = blog_colors$blue\n  )) +\n  theme_blog() +\n  theme(legend.position = \"bottom\") +\n  labs(x = \"Correlation in cell (2, 1)\", y = \"Density\",\n       color = NULL, fill = NULL,\n       title = \"Bounded LKJ Marginals\")\n```\n\n::: {.cell-output-display}\n![Marginal draws for the first lower-triangular cell, Omega[2,1], under each pair of transforms.](corr-bounds_files/figure-html/fig-selected-marginals-1.png){#fig-selected-marginals width=960}\n:::\n:::\n\n\n### 7.3 Feasibility and HMC Performance in These Runs\n\nAcross the 54,000 retained matrices, the checks recorded no bound violations. The smallest sampled eigenvalue was positive in every fit, and there were no maximum-treedepth hits. Every sampled raw coordinate, including `direction_raw` and `radius_raw`, and every reported off-diagonal correlation had $\\widehat R<1.004$. The triangular sign map had no divergences in these runs. The global ray had one divergence in the mixed-sign case. A single divergent transition does not identify its cause; the piecewise boundary is one possible mechanism.\n\n\n::: {#tbl-diagnostics .cell}\n\n```{.r .cell-code}\ndiagnostics |>\n  transmute(\n    Scenario = scenario_label,\n    Transform = model_label,\n    Divergences = divergences,\n    `Min bulk ESS` = round(pmin(min_bulk_ess, min_parameter_bulk_ess)),\n    `Min corr ESS / 1k leapfrog steps` = round(ess_per_1000_gradients, 1),\n    `Min E-BFMI` = round(min_ebfmi, 2),\n    `Max R-hat` = round(pmax(max_rhat, max_parameter_rhat), 3),\n    `PD boundary (%)` = ifelse(\n      is.na(pd_boundary_fraction),\n      \"--\",\n      sprintf(\"%.1f\", 100 * pd_boundary_fraction)\n    ),\n    `Time (s)` = round(seconds, 2),\n    `Min eigenvalue` = signif(min_eigenvalue, 3)\n  ) |>\n  knitr::kable(align = c(\"l\", \"l\", rep(\"r\", 8)))\n```\n\n::: {.cell-output-display}\n\n\n|Scenario                    |Transform            | Divergences| Min bulk ESS| Min corr ESS / 1k leapfrog steps| Min E-BFMI| Max R-hat| PD boundary (%)| Time (s)| Min eigenvalue|\n|:---------------------------|:--------------------|-----------:|------------:|--------------------------------:|----------:|---------:|---------------:|--------:|--------------:|\n|All positive                |Triangular sign      |           0|         3877|                             59.7|       0.87|     1.002|              --|     0.27|       0.002950|\n|All positive                |Global ray           |           0|         3049|                              5.7|       0.78|     1.001|            59.4|     1.19|       0.000582|\n|All negative                |Triangular sign      |           0|         5492|                            122.7|       0.81|     1.002|              --|     0.15|       0.000375|\n|All negative                |Global ray           |           0|         1877|                              1.3|       0.78|     1.003|            42.9|     3.17|       0.001600|\n|Mixed signs                 |Triangular sign      |           0|         4585|                            103.2|       0.91|     1.001|              --|     0.14|       0.003020|\n|Mixed signs                 |Global ray           |           1|         1900|                              1.3|       0.71|     1.003|            66.2|     2.65|       0.002780|\n|Certified heterogeneous box |Certified direct box |           0|         8040|                            187.0|       0.83|     1.004|              --|     0.15|       0.417000|\n|Certified heterogeneous box |Global ray           |           0|         2505|                              3.4|       0.71|     1.001|             0.0|     1.62|       0.421000|\n|Wide heterogeneous box      |Global ray           |           0|         3299|                              7.1|       0.82|     1.001|             4.5|     1.08|       0.003540|\n\n\n:::\n:::\n\n\nThe global construction was less efficient in these runs. It needs an eigendecomposition at every log-density evaluation, carries one auxiliary radial parameter, and uses the piecewise ray limit. Its minimum bulk ESS over the ten reported correlation cells per 1,000 recorded leapfrog steps was between 1.3 and 7.1, versus 59.7--122.7 for the triangular sign map and 187.0 for the certified direct box. The positive-definite boundary was active for 4.5% of the wide-box draws and was not active in the retained draws from the spectrally certified box.\n\n## 8. What to Use\n\nFor an all-positive, all-negative, or prespecified mixed-sign pattern, I would start with the **triangular sign transform**. The formulas and row-wise inverse in Section 3 give a smooth bijection onto the interior of the signed elliptope. In exact arithmetic, every finite unconstrained state therefore produces a positive-definite correlation matrix with the requested signs, and every matrix in that constrained interior is represented. The calculation is triangular, with no eigendecomposition, auxiliary radial variable, or minimum over competing boundary distances.\n\nThe numerical comparison is consistent with that preference. In the three $K=5$ sign experiments, the triangular map produced no divergences and achieved 59.7--122.7 minimum bulk ESS over the ten correlation cells per 1,000 recorded leapfrog steps. The global ray achieved 1.3--5.7 on the same targets and had one divergence in the mixed-sign case. These runs do not establish a general performance ordering. Coverage instead follows from the inverse maps in Sections 3 and 4: both maps represent the same sign-constrained interiors. The triangular construction is therefore my default for sign-only models.\n\nAn exact fixed value specifies a magnitude, not merely a sign. The affine triangular transform handles an individual row whenever the Schur-complement condition in Section 5 holds; if the predecessor block is fixed, that condition can be checked in advance. For a general pattern, however, the sequential construction can encounter internal prefix boundaries. Given a strict anchor, the reduced global ray avoids those prefix failures because it holds the fixed cells constant while exploring the feasible slice.\n\nThe other constructions handle positive-width finite intervals that the sign transform does not express. A cell-specific cap such as $0<\\rho_{ij}<u_{ij}<1$, or a finite interval $\\ell_{ij}<\\rho_{ij}<u_{ij}$, is more than a sign constraint. If the entire resulting box can be certified positive definite, independent logits give the simpler smooth parameterization. Otherwise, if a strict anchor is available, the global ray covers the interior of the box--elliptope intersection at the cost of piecewise geometry and an eigendecomposition at every density evaluation.\n\nOne final qualification concerns $\\eta$. Everything here treats the LKJ shape as fixed. For a bounded region or affine equality slice $\\mathcal A$, the relevant normalizing integral is\n\n$$Z_{\\mathcal A}(\\eta)\n=\\int_{\\mathcal A}\\det(\\Omega)^{\\eta-1}\\,d\\mu_{\\mathcal A}(\\Omega),$$\n\nwhere $\\mu_{\\mathcal A}$ is Lebesgue measure on the remaining free correlations. If $\\eta$ is inferred, $Z_{\\mathcal A}(\\eta)$ generally depends on $\\eta$ and cannot be dropped unless it is shown to be constant for the particular slice. The determinant kernel and change-of-variables Jacobian alone are sufficient here because $\\eta$ is fixed.\n\n## Reproducibility\n\nThe main benchmark is in [`benchmark_bounds.R`](benchmark_bounds.R); the exact-value rejection check is in [`benchmark_fixed_values.R`](benchmark_fixed_values.R). The downloadable [`tri-sign`](tri-sign-corr-bounds.stan), [`global-ray`](global-ray-corr-bounds.stan), and [`certified-box`](direct-certified-box-corr.stan) Stan programs are in the same published directory. The global-ray program accepts both positive-width intervals and exact cells; the other two programs retain their narrower interfaces. Each script checks its applicable bounds or fixed values and sampled eigenvalues, and records the sampler diagnostics reported above.\n\nThe published results are the main [`diagnostics`](bounds-diagnostics.csv), [`cell summaries`](bounds-cell-summary.csv), [`scenario bounds`](bounds-scenarios.csv), and [`plotted draw subset`](bounds-selected-draws.csv), together with the fixed-value [`diagnostics`](fixed-values-diagnostics.csv) and [`comparison`](fixed-values-summary.csv). Run settings and source checksums are recorded in [`bounds-run-settings.csv`](bounds-run-settings.csv), [`bounds-source-hashes.csv`](bounds-source-hashes.csv), [`fixed-values-run-settings.csv`](fixed-values-run-settings.csv), and [`fixed-values-source-hashes.csv`](fixed-values-source-hashes.csv).\n\n## Appendix: Stan Implementations\n\n::: panel-tabset\n### Triangular sign transform\n\n``` {.stan filename=\"tri-sign-corr-bounds.stan\"}\n/*\n  Smooth triangular transform for prescribed correlation signs.\n\n  Every off-diagonal cell is either positive, with bounds [0, 1], or\n  negative, with bounds [-1, 0].  In Cholesky row i, let B be the leading\n  Cholesky block and c the ordinary correlations with earlier variables.\n  The transform creates a vector x in the requested orthant, solves\n\n      w = B^{-1} x,\n\n  and applies the modified stereographic hemisphere map\n\n      z = sqrt(w'w + 2) / (w'w + 1) * w,\n      L[i,i] = 1 / (w'w + 1).\n\n  Because c = B z is a positive scalar multiple of x, every requested sign\n  is exact and every raw value produces a positive-definite correlation\n  matrix.  The B and B^{-1} determinants cancel in the raw-to-c Jacobian.\n*/\n\nfunctions {\n  tuple(matrix, real) corr_cholesky_sign_jacobian(\n      int K,\n      vector raw,\n      matrix corr_lower,\n      matrix corr_upper) {\n    matrix[K, K] L = rep_matrix(0.0, K, K);\n    int raw_pos = 1;\n    real log_det = 0.0;\n    real input_scale = 2.0 * K;\n\n    L[1, 1] = 1.0;\n\n    for (i in 2:K) {\n      int d = i - 1;\n      vector[d] x;\n      matrix[d, d] previous_cholesky = L[1:d, 1:d];\n\n      for (j in 1:d) {\n        real raw_ij = raw[raw_pos + j - 1];\n        real magnitude = log1p_exp(raw_ij) / input_scale;\n        real sign_ij = corr_lower[i, j] == 0.0 ? 1.0 : -1.0;\n\n        x[j] = sign_ij * magnitude;\n        jacobian += log_inv_logit(raw_ij) - log(input_scale);\n      }\n\n      {\n        vector[d] w = mdivide_left_tri_low(previous_cholesky, x);\n        real t = dot_self(w);\n        real scale = sqrt(t + 2.0) / (t + 1.0);\n\n        L[i, 1:d] = (scale * w)';\n        L[i, i] = 1.0 / (t + 1.0);\n        log_det += 2.0 * log(L[i, i]);\n\n        // Exact determinant of w -> scale(t) * w.  The constant log(2)\n        // is retained even though it could be dropped from the target.\n        jacobian += log(2.0)\n                    + 0.5 * (d - 2.0) * log(t + 2.0)\n                    - (d + 1.0) * log1p(t);\n      }\n\n      raw_pos += d;\n    }\n\n    if (raw_pos != num_elements(raw) + 1) {\n      reject(\"Sign transform consumed \", raw_pos - 1,\n             \" raw values but received \", num_elements(raw), \".\");\n    }\n\n    return (L, log_det);\n  }\n}\n\ndata {\n  int<lower=2> K;\n  real<lower=0> eta;\n  matrix[K, K] corr_lower;\n  matrix[K, K] corr_upper;\n  real<lower=0> validation_tolerance;\n}\n\ntransformed data {\n  if (!(eta > 0.0)) {\n    reject(\"The LKJ shape eta must be strictly positive; received \", eta,\n           \".\");\n  }\n\n  for (i in 1:K) {\n    if (abs(corr_lower[i, i] - 1.0) > validation_tolerance\n        || abs(corr_upper[i, i] - 1.0) > validation_tolerance) {\n      reject(\"Both bound matrices must equal one on diagonal \", i, \".\");\n    }\n\n    if (i > 1) {\n      for (j in 1:(i - 1)) {\n        real lo = corr_lower[i, j];\n        real hi = corr_upper[i, j];\n        int positive_sign = lo == 0.0 && hi == 1.0;\n        int negative_sign = lo == -1.0 && hi == 0.0;\n\n        if (abs(lo - corr_lower[j, i]) > validation_tolerance\n            || abs(hi - corr_upper[j, i]) > validation_tolerance) {\n          reject(\"Bounds are not symmetric at pair (\", i, \",\", j, \").\");\n        }\n        if (!(positive_sign || negative_sign)) {\n          reject(\"Pair (\", i, \",\", j,\n                 \") must request [0,1] or [-1,0]; received [\",\n                 lo, \",\", hi, \"].\");\n        }\n      }\n    }\n  }\n}\n\nparameters {\n  vector[choose(K, 2)] raw;\n}\n\ntransformed parameters {\n  matrix[K, K] L_Omega;\n  corr_matrix[K] Omega;\n  real log_det_Omega;\n\n  {\n    tuple(matrix[K, K], real) result = corr_cholesky_sign_jacobian(\n        K, raw, corr_lower, corr_upper);\n    L_Omega = result.1;\n    log_det_Omega = result.2;\n    Omega = multiply_lower_tri_self_transpose(L_Omega);\n  }\n}\n\nmodel {\n  target += (eta - 1.0) * log_det_Omega;\n}\n\n```\n\n### Global anchor ray\n\n``` {.stan filename=\"global-ray-corr-bounds.stan\"}\n/*\n  Globally feasible transform for arbitrary elementwise correlation bounds\n  and exact fixed ordinary correlations.\n\n  The feasible set is the intersection of the positive-definite correlation\n  cone and an ordinary-correlation box.  Given a strictly interior anchor,\n  every ray from that anchor remains feasible until it first reaches either a\n  box face or the positive-definite boundary.  Cells whose lower and upper\n  bounds are exactly equal are held fixed and omitted from the direction\n  vector.  An auxiliary isotropic normal vector supplies a uniform direction\n  on the sphere of the remaining free coordinates; its radius is independent\n  of the resulting correlation matrix.\n\n  The target is det(Omega)^(eta - 1) with respect to the remaining free\n  ordinary off-diagonal correlations.\n*/\n\nfunctions {\n  tuple(matrix, real, real, real, real) corr_global_ray_jacobian(\n      vector direction_raw,\n      real radius_raw,\n      matrix corr_lower,\n      matrix corr_upper,\n      matrix anchor,\n      matrix anchor_cholesky) {\n    int K = rows(anchor);\n    int D = num_elements(direction_raw);\n    real direction_norm = sqrt(dot_self(direction_raw));\n    vector[D] direction;\n    matrix[K, K] direction_matrix = rep_matrix(0.0, K, K);\n    real max_radius_box = positive_infinity();\n    real max_radius_pd = positive_infinity();\n    real max_radius;\n    real radius_fraction = inv_logit(radius_raw);\n    real radius;\n    matrix[K, K] Omega;\n    real log_det;\n    int pos = 1;\n\n    if (!(direction_norm > 0.0)) {\n      reject(\"The auxiliary direction vector has zero norm.\");\n    }\n    if (!(radius_fraction > 0.0 && radius_fraction < 1.0)) {\n      reject(\"The radial inverse logit reached an endpoint; raw value=\",\n             radius_raw, \".\");\n    }\n\n    direction = direction_raw / direction_norm;\n\n    for (i in 2:K) {\n      for (j in 1:(i - 1)) {\n        if (corr_lower[i, j] != corr_upper[i, j]) {\n          real component = direction[pos];\n          real distance_to_face;\n\n          direction_matrix[i, j] = component;\n          direction_matrix[j, i] = component;\n\n          if (component > 0.0) {\n            distance_to_face = (corr_upper[i, j] - anchor[i, j])\n                               / component;\n            max_radius_box = fmin(max_radius_box, distance_to_face);\n          } else if (component < 0.0) {\n            distance_to_face = (corr_lower[i, j] - anchor[i, j])\n                               / component;\n            max_radius_box = fmin(max_radius_box, distance_to_face);\n          }\n\n          pos += 1;\n        }\n      }\n    }\n\n    if (pos != D + 1) {\n      reject(\"Global-ray transform consumed \", pos - 1,\n             \" free direction values but received \", D, \".\");\n    }\n\n    // C(t) = C0 + t*S is positive definite exactly while\n    // I + t * L0^{-1} S L0^{-T} is positive definite.\n    {\n      matrix[K, K] left_solve = mdivide_left_tri_low(\n          anchor_cholesky, direction_matrix);\n      matrix[K, K] standardized_direction = mdivide_left_tri_low(\n          anchor_cholesky, left_solve')';\n      vector[K] eigenvalues = eigenvalues_sym(\n          0.5 * (standardized_direction + standardized_direction'));\n      real lambda_min = eigenvalues[1];\n\n      if (lambda_min < 0.0) {\n        max_radius_pd = -1.0 / lambda_min;\n      }\n      max_radius = fmin(max_radius_box, max_radius_pd);\n    }\n\n    if (!(max_radius > 0.0) || is_inf(max_radius)) {\n      reject(\"The supplied anchor has no finite positive ray in this \",\n             \"direction; max_radius=\", max_radius, \".\");\n    }\n\n    radius = radius_fraction * max_radius;\n    Omega = anchor + radius * direction_matrix;\n\n    {\n      matrix[K, K] L = cholesky_decompose(Omega);\n      log_det = 2.0 * sum(log(diagonal(L)));\n    }\n\n    // In D dimensions, dc = radius^(D-1) d(radius) d(surface).\n    // Normalizing an isotropic standard-normal auxiliary vector supplies\n    // uniform surface measure, so only the ray and logistic terms remain.\n    jacobian += (D - 1.0) * log(radius)\n                + log(max_radius)\n                + log_inv_logit(radius_raw)\n                + log1m_inv_logit(radius_raw);\n\n    return (Omega, log_det, max_radius, max_radius_box, max_radius_pd);\n  }\n}\n\ndata {\n  // With only one free cell, at any K, the unit direction is the\n  // discontinuous sign of one scalar; use a direct bounded logistic for\n  // that one-dimensional special case.\n  int<lower=3> K;\n  real<lower=0> eta;\n  int<lower=0, upper=choose(K, 2)> N_fixed;\n  matrix[K, K] corr_lower;\n  matrix[K, K] corr_upper;\n  corr_matrix[K] anchor;\n  real<lower=0> validation_tolerance;\n}\n\ntransformed data {\n  matrix[K, K] anchor_cholesky = cholesky_decompose(anchor);\n  int fixed_count = 0;\n  int D_free = choose(K, 2) - N_fixed;\n\n  if (!(eta > 0.0)) {\n    reject(\"The LKJ shape eta must be strictly positive; received \", eta,\n           \".\");\n  }\n  if (D_free < 2) {\n    reject(\"The normalized-direction global-ray transform requires at least \",\n           \"two free correlations; received \", D_free, \".\");\n  }\n\n  for (i in 1:K) {\n    if (abs(corr_lower[i, i] - 1.0) > validation_tolerance\n        || abs(corr_upper[i, i] - 1.0) > validation_tolerance) {\n      reject(\"Both bound matrices must equal one on diagonal \", i, \".\");\n    }\n\n    if (i > 1) {\n      for (j in 1:(i - 1)) {\n        real lo = corr_lower[i, j];\n        real hi = corr_upper[i, j];\n\n        if (abs(lo - corr_lower[j, i]) > validation_tolerance\n            || abs(hi - corr_upper[j, i]) > validation_tolerance) {\n          reject(\"Bounds are not symmetric at pair (\", i, \",\", j, \").\");\n        }\n        if (lo < -1.0 || hi > 1.0 || lo > hi) {\n          reject(\"Pair (\", i, \",\", j,\n                 \") must have ordered bounds inside [-1,1]; got [\",\n                 lo, \",\", hi, \"].\");\n        }\n\n        if (lo == hi) {\n          fixed_count += 1;\n          if (anchor[i, j] != lo) {\n            reject(\"Anchor must equal the exact fixed value at pair (\", i,\n                   \",\", j, \"): anchor=\", anchor[i, j],\n                   \", fixed value=\", lo, \".\");\n          }\n        } else {\n          if (!(anchor[i, j] > lo + validation_tolerance\n                && anchor[i, j] < hi - validation_tolerance)) {\n            reject(\"Anchor is not strictly inside the bounds at pair (\", i,\n                   \",\", j, \"): anchor=\", anchor[i, j], \", bounds=[\",\n                   lo, \",\", hi, \"].\");\n          }\n        }\n      }\n    }\n  }\n\n  if (fixed_count != N_fixed) {\n    reject(\"N_fixed declares \", N_fixed, \" exact cells, but the lower and \",\n           \"upper bound matrices contain \", fixed_count,\n           \" equal off-diagonal pairs.\");\n  }\n}\n\nparameters {\n  vector[choose(K, 2) - N_fixed] direction_raw;\n  real radius_raw;\n}\n\ntransformed parameters {\n  corr_matrix[K] Omega;\n  real log_det_Omega;\n  real max_radius;\n  real max_radius_box;\n  real max_radius_pd;\n  real pd_boundary_active;\n\n  {\n    tuple(matrix[K, K], real, real, real, real) result\n        = corr_global_ray_jacobian(\n            direction_raw, radius_raw,\n            corr_lower, corr_upper, anchor, anchor_cholesky);\n    Omega = result.1;\n    log_det_Omega = result.2;\n    max_radius = result.3;\n    max_radius_box = result.4;\n    max_radius_pd = result.5;\n    pd_boundary_active = max_radius_pd < max_radius_box ? 1.0 : 0.0;\n  }\n}\n\nmodel {\n  // The auxiliary radius integrates out independently; isotropy makes the\n  // normalized direction uniform on the sphere.\n  direction_raw ~ std_normal();\n  target += (eta - 1.0) * log_det_Omega;\n}\n\n```\n\n### Certified direct box\n\n``` {.stan filename=\"direct-certified-box-corr.stan\"}\n/*\n  Direct ordinary-correlation transform for a box certified to lie entirely\n  inside the positive-definite correlation cone.\n\n  This model deliberately performs no feasibility look-ahead.  It is valid\n  only when the supplied box has been certified externally (for example with\n  a spectral-norm/Weyl bound around a positive-definite anchor).\n*/\n\ndata {\n  int<lower=2> K;\n  real<lower=0> eta;\n  matrix[K, K] corr_lower;\n  matrix[K, K] corr_upper;\n  real<lower=0> validation_tolerance;\n}\n\ntransformed data {\n  if (!(eta > 0.0)) {\n    reject(\"The LKJ shape eta must be strictly positive; received \", eta,\n           \".\");\n  }\n\n  for (i in 1:K) {\n    if (abs(corr_lower[i, i] - 1.0) > validation_tolerance\n        || abs(corr_upper[i, i] - 1.0) > validation_tolerance) {\n      reject(\"Both bound matrices must equal one on diagonal \", i, \".\");\n    }\n\n    if (i > 1) {\n      for (j in 1:(i - 1)) {\n        real lo = corr_lower[i, j];\n        real hi = corr_upper[i, j];\n\n        if (abs(lo - corr_lower[j, i]) > validation_tolerance\n            || abs(hi - corr_upper[j, i]) > validation_tolerance) {\n          reject(\"Bounds are not symmetric at pair (\", i, \",\", j, \").\");\n        }\n        if (lo < -1.0 || hi > 1.0 || !(lo < hi)) {\n          reject(\"Pair (\", i, \",\", j,\n                 \") must have positive-width bounds inside [-1,1]; got [\",\n                 lo, \",\", hi, \"].\");\n        }\n      }\n    }\n  }\n}\n\nparameters {\n  vector[choose(K, 2)] raw;\n}\n\ntransformed parameters {\n  corr_matrix[K] Omega;\n  real log_det_Omega;\n\n  {\n    matrix[K, K] work = identity_matrix(K);\n    int pos = 1;\n\n    for (i in 2:K) {\n      for (j in 1:(i - 1)) {\n        real value = lower_upper_bound_jacobian(\n            raw[pos], corr_lower[i, j], corr_upper[i, j]);\n        work[i, j] = value;\n        work[j, i] = value;\n        pos += 1;\n      }\n    }\n\n    Omega = work;\n    log_det_Omega = log_determinant_spd(Omega);\n  }\n}\n\nmodel {\n  target += (eta - 1.0) * log_det_Omega;\n}\n\n```\n:::\n",
    "supporting": [
      "corr-bounds_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}