{
  "hash": "936b24489e3c9796d47b441f8db6983e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Structural Zeros in Correlation Matrices: A Thirteen-Parameterization Bake-Off\"\nauthor: \"Sean Pinkney\"\ndate: \"2026-07-15\"\ndate-modified: \"2026-08-08\"\ncategories: [stan, correlation, parameterizations]\nbibliography: references.bib\nformat:\n  html:\n    code-fold: true\n---\n\n## 1. The Problem with Zeros in Correlation Matrices\n\nSometimes you know, before seeing any data, that certain correlations are exactly zero. For example, a priori knowledge that two variables are *marginally*^[[\\@ethothepie.bsky.social](https://bsky.app/profile/ethothepie.bsky.social) corrected the original here where I incorrectly implied the zeros in the correlation matrix are conditionally unrelated when this is marginal] unrelated occurs in graphical models as either an explicit assumption or by pre-existing knowledge that rules out the variable coupling. Building this structure directly through the correlation matrix parameterization is what this blog post is about.\n\nSampling from an LKJ prior and setting selected cells to zero does not work because the resulting matrix will generally not be positive definite. Instead, the zeros have to be part of the parameterization. In this post I compare thirteen Stan [@carpenter2017] implementations that target the same distribution. I check that they agree numerically, then compare divergences, effective sample size, gradient evaluations, and run time.\n\nThe implementations fall into two groups. The first imposes the zero equalities sequentially in Cholesky or C-vine coordinates. The second samples each row in the subspace satisfying all of its zero constraints. I also introduce a triangular basis for the second approach. In these examples it removes the divergences seen in the entry-wise construction without the loss of efficiency I found with a QR basis.\n\n## 2. Family 1: Forced Zeros\n\nSeven members of the first group use the constrained-Cholesky approach I introduced in @pinkney2024 and presented at StanCon [@pinkneytalk]. The original method also allows a correlation to be fixed at a nonzero value or restricted to an interval. Writing $\\Omega = L L'$ with unit-norm rows of $L$, the correlation in cell $(i,j)$ is $$\n\\Omega_{ij} = b_1 + L_{ij} L_{jj}, \\qquad\nb_1 = \\sum_{k<j} L_{ik} L_{jk},\n$$ This is affine in $L_{ij}$, so setting the correlation to zero gives $L_{ij}=-b_1/L_{jj}$ and uses no parameter. A bound on $\\Omega_{ij}$ similarly becomes a bound on $L_{ij}$. Conditioning on $\\Omega_{ij}=0$ contributes $-\\log L_{jj}$ to the log density for each zero. The `carpenter` variant below is Bob Carpenter's compact formulation of this case from a [Stan Discourse discussion](https://discourse.mc-stan.org/t/new-users-guide-intro-sem-and-user-defined-constrained-parameters-chapters/41430):\n\n``` stan\nif (is_zero(i, j, zeros, zero_idx)) {\n  real b = dot_product(L[j, 1:(j - 1)], L[i, 1:(j - 1)]);\n  L[i, j] = -b / L[j, j];   // implies Omega[i, j] == 0\n  jacobian += -log(L[j, j]);\n  zero_idx += 1;\n}\n```\n\nThe free entries can be parameterized in several ways. I compare the following nine variants:\n\n| label | free-cell parameterization |\n|:-----------------------------------|:-----------------------------------|\n| `carpenter` | direct Cholesky entries, bounded by the remaining stick |\n| `pinkney` | correlation-scale value divided by $L_{jj}$, multiplicative stick [@pinkney2024; @pinkneytalk] |\n| `ldl` / `ldl2` / `ldl3` | $LDL'$ factorization [@pinkney2024]; stick tracked via `log_diff_exp`, a `log1m` ratio, or the natural scale |\n| `cvine` | C-vine partial correlations with the LKJ Beta factorization [@joe2006; @lewandowski2009] |\n| `cvine_lookahead` | exact equality coordinates, all-future 3-by-3 look-ahead, and a reduced free-cell Jacobian |\n| `rowscale` | direct Cholesky entries, row-scaling stick |\n| `schur` | canonical partial correlations, $L_{ij} = r \\tanh(x)$ |\n\nThe seven Cholesky and $LDL'$ variants share the same constraint. The value $-b_1/L_{jj}$ is computed without reference to the remaining row norm, $\\sqrt{1 - \\sum_{k<j} L_{ik}^2}$, and can exceed the available range. A later square root then receives a negative argument. In the $K=7$ benchmarks below, these variants have divergences in about 1% of post-warmup transitions.\n\nThe [`cvine_lookahead` model](https://gist.github.com/spinkney/7d994fb03079c9edb8a0e83a40d2faad) instead represents every zero as an exact ordinary-correlation equality, omits those coordinates from the parameter vector, and uses exact $3\\times3$ elliptope projections to narrow each free partial-correlation interval before sampling it. Its Jacobian contains only the free ordinary-correlation coordinates, and the LKJ kernel is added through $(\\eta-1)\\log\\det(\\Omega)$. The look-ahead substantially reduces infeasible proposals, although it does not remove every nonlocal feasibility boundary for dense patterns.\n\nThe three LDL variants are also useful for judging Monte Carlo variability. They define the same density and differ only in how some floating-point operations are arranged, but their total divergences over five patterns range from 356 to 466. Differences of that size should not be interpreted as evidence that one parameterization is better from a single set of fits.\n\n## 3. Family 2: Exact-Constraint Subspaces\n\nThe second approach comes from Seth Axen's Turing.jl discussion of positive definite matrices with structural zeros [@axen2023]:\n\n> For each column j, each column i for i \\< j that is orthogonal to column j decreases the dimensionality of the hemisphere by 1. So we simply construct a point on a lower dimensional hemisphere and use the QR decomposition of the orthogonal columns to lift it to a higher dimensional hemisphere.\n\nRow $i$ of a correlation Cholesky factor is a unit vector with a positive diagonal element. Since row $j$ is zero after column $j$, the condition $\\Omega_{ij}=0$ is equivalent to requiring rows $i$ and $j$ to be orthogonal. If row $i$ has $n_z$ constrained correlations, it can be sampled on the unit hemisphere in the orthogonal complement of those $n_z$ rows. The dimension of this hemisphere is $d=i-1-n_z$. The joint conditioning term for the row is $-\\tfrac12\\log\\det(A'A)$, where the columns of $A$ are the rows to which it must be orthogonal.\n\nMy first two implementations, `qr` and `qr2`, construct this complement with a Householder QR decomposition. They use either a gnomonic map or the hyper-tanh peel [@pinkney2026] for the hemisphere coordinates. Both models have zero divergences in the $K=7$ benchmark, but their minimum ESS is about 40% of the entry-wise models. Changing the hemisphere map has little effect. The larger difference comes from the complement basis: the trailing columns of $Q$ change as the preceding rows change, so the interpretation of the unconstrained coordinates also changes during sampling.\n\n## 4. A Canonical Triangular Basis\n\nI instead construct a basis tied to the free matrix entries. For each free column $k$ of row $i$, I start with the coordinate vector $e_k$ and solve for the constrained columns by back-substitution. This is the entry-wise construction from the previous section applied to a basis vector rather than to the sampled row. If $Z$ and $F$ denote the constrained and free columns, the resulting basis matrix $T$ satisfies $T_F=I$ and $T_Z=-(A_Z')^{-1}A_F'$.\n\nTo orthonormalize this basis, let $S=\\operatorname{chol}(T'T)$. Then $v=T(S')^{-1}z$ preserves the norm of $z$. I parameterize $z$ using the row transformation from @pinkney2025. With $t=y'y$, $$\nz = \\frac{\\sqrt{t+2}}{t+1}y, \\qquad L_{ii}=\\frac{1}{t+1},\n$$ and the log Jacobian is $\\tfrac12(d-2)\\log(t+2)-(d+1)\\log(1+t)$.\n\nTwo identities reduce the amount of linear algebra required.\n\n1.  The zero-partner rows have triangular support, so $A_Z$ is triangular with the partners' diagonals on its diagonal. Sylvester's determinant identity gives $$\n    \\det(A'A) = \\Big(\\prod_{j \\in Z} L_{jj}\\Big)^{2} \\det(T'T).\n    $$ Thus $-\\tfrac12\\log\\det(A'A)$ becomes $-\\sum_j\\log L_{jj}-\\sum_k\\log S_{kk}$. The second term is available from the Cholesky factor already used to orthonormalize $T$.\n\n2.  Since $T_F=I$, $T'T=I+W'W$, where $W$ contains only the $n_z$ constrained rows. The cross-product therefore uses vectors of length $n_z$ rather than $i-1$.\n\nEach constrained row requires one $d\\times d$ `cholesky_decompose` and several matrix-vector products. I call this model `tri`; the Stan code is in the appendix.\n\nI also test an over-parameterized version, called `donut`, that uses one additional parameter per row. It normalizes a free vector, $u=y/\\lVert y\\rVert$, before mapping it into the constrained subspace. The normalization is rotationally symmetric but singular at the origin. Following @axen2022, I replace the usual radial term $-\\tfrac12\\lVert y\\rVert^2$ with $-\\tfrac12(\\lVert y\\rVert-m)^2$ so that the typical radius is away from zero. Since this term only changes the radius, it does not change the induced distribution on $\\Omega$. The largest difference in a free-cell posterior mean relative to `carpenter` is 0.0046. Across the five $K=7$, $\\eta=4$ patterns:\n\n| radial prior | total divergences | median min ESS | median ESS / 1k gradients |\n|:-------------------|-----------------:|-----------------:|-----------------:|\n| $m = 0$ (implicit chi) | 2,549 | 4,778 | 19 |\n| $m = 2$ | 349 | 8,106 | 80 |\n| $m = 4$ | 8 | 10,778 | 192 |\n| $m = 6$ | **0** | 9,045 | 162 |\n\nIncreasing $m$ removes the divergences and improves efficiency up to $m=4$; $m=6$ gives zero divergences in these runs. I use $m=6$ below. The `tri` model does not require this additional choice and uses $K-1$ fewer parameters.\n\n## 5. The Bake-Off at K = 7\n\nSetup: $K = 7$, $\\eta = 4$, prior-only, five random zero patterns with roughly half of the 21 lower-triangular cells zeroed, 4 chains $\\times$ 2000 draws after 1000 warmup, default `adapt_delta = 0.8`. Correctness was checked on a held-out pattern first: all thirteen posteriors match the `carpenter` baseline within Monte Carlo error, and the constrained cells come back as numerically exact zeros ($\\sim 10^{-19}$).\n\n**Divergences** out of 8,000 post-warmup transitions:\n\n| pattern | carpenter | pinkney | ldl | ldl2 | cvine | cvine_lookahead | rowscale | ldl3 | schur | qr | qr2 | tri | donut |\n|:-----|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|\n| seed 1 | 34 | 53 | 53 | 26 | 41 | 0 | 44 | 40 | 40 | 0 | 0 | **0** | 0 |\n| seed 2 | 61 | 65 | 74 | 107 | 64 | 0 | 78 | 104 | 60 | 0 | 0 | **0** | 0 |\n| seed 3 | 77 | 44 | 67 | 57 | 69 | 1 | 44 | 68 | 59 | 0 | 0 | **0** | 0 |\n| seed 4 | 137 | 157 | 130 | 112 | 186 | 0 | 155 | 152 | 123 | 0 | 0 | **0** | 0 |\n| seed 5 | 110 | 94 | 114 | 54 | 141 | 7 | 114 | 102 | 29 | 0 | 0 | **0** | 0 |\n| **total** | 419 | 413 | 438 | 356 | 501 | 8 | 435 | 466 | 311 | **0** | **0** | **0** | **0** |\n\n**Min bulk ESS** over the free cells of $\\Omega$ (8,000 draws):\n\n| pattern | carpenter | pinkney | ldl | ldl2 | cvine | cvine_lookahead | rowscale | ldl3 | schur | qr | qr2 | tri | donut |\n|:-----|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|\n| seed 1 | 11639 | 10566 | 9979 | 10618 | 10219 | 11572 | 11319 | 9840 | 11036 | 3995 | 3362 | **11238** | 10676 |\n| seed 2 | 10817 | 9866 | 10826 | 9772 | 10188 | 12308 | 10153 | 10361 | 10040 | 4049 | 3728 | **11923** | 9045 |\n| seed 3 | 9344 | 11014 | 10244 | 10314 | 10946 | 9535 | 9420 | 10625 | 10787 | 4334 | 4304 | 10655 | 9429 |\n| seed 4 | 8395 | 9159 | 8326 | 9257 | 8771 | 9224 | 9463 | 8266 | 9458 | 3701 | 3815 | **9400** | 8161 |\n| seed 5 | 10381 | 10010 | 9268 | 8760 | 10301 | 10454 | 9218 | 9896 | 4770 | 4267 | 4153 | **11845** | 8619 |\n| **median** | 10381 | 10010 | 9979 | 9772 | 10219 | 10454 | 9463 | 9896 | 10040 | 4049 | 3815 | **11238** | 9045 |\n\n**Efficiency** (medians over the five patterns):\n\n|   | carpenter | pinkney | ldl | ldl2 | cvine | cvine_lookahead | rowscale | ldl3 | schur | qr | qr2 | tri | donut |\n|:-----|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|\n| min ESS / 1000 gradients | 188.5 | 179.6 | 185.9 | 182.2 | 188.9 | 194.1 | 176.3 | 182.1 | 182.0 | 75.0 | 72.5 | **212.3** | 161.8 |\n| total wall clock, 5 fits (s) | 4.53 | 4.10 | 4.40 | 4.51 | 5.14 | 2.65 | 4.21 | 4.51 | 4.15 | 2.07 | 2.06 | **1.86** | 2.39 |\n\nThe `cvine_lookahead` model records 8 divergences across the five patterns, compared with 501 for `cvine`, and completes the five fits in 2.65 rather than 5.14 seconds. The `tri` model still has zero divergences for all five patterns, the highest median minimum ESS, the highest median ESS per 1,000 gradients, and the shortest total run time. The QR models also remove divergences, but their changing complement basis produces substantially lower ESS. The triangular basis avoids that loss in this benchmark.\n\n## 6. What the Look-Ahead Changes: `cvine` vs `cvine_lookahead`\n\nThe original `cvine` samples the unconstrained C-vine partial correlations from their LKJ Beta factors. When an ordinary correlation is fixed to zero, it solves the affine partial-correlation recursion for the required value. Nothing restricts earlier free partials to ensure that the solution will remain in $(-1,1)$, so the transform can meet a feasibility boundary late in the recursion.\n\n`cvine_lookahead` carries intervals for the unsampled conditional correlations. Before selecting the current partial correlation $x$, it uses the exact $3\\times3$ condition\n\n$$\n1 + 2xyr - x^2 - y^2 - r^2 \\ge 0\n$$\n\nto project every later pair onto a feasible interval for $x$. After selecting $x$, it tightens the later intervals and continues. Fixed ordinary correlations are point intervals, so zeros take no raw parameter in either model. The new transform uses the reduced Jacobian from raw values to the free ordinary correlations and adds the LKJ kernel as $(\\eta-1)\\log\\det(\\Omega)$; it therefore targets the same conditional LKJ distribution as `cvine`.\n\n| $K=7$, $\\eta=4$, five patterns | `cvine` | `cvine_lookahead` |\n|:---------------------------------|--------:|------------------:|\n| total divergences | 501 | **8** |\n| median minimum bulk ESS | 10,219 | **10,454** |\n| median ESS / 1,000 gradients | 188.9 | **194.1** |\n| total wall clock (s) | 5.14 | **2.65** |\n\nThe scaling sweep tells the same story. The original initializes in 12 of 20 configurations and fails for every $K=15$ and $K=25$ fit. `cvine_lookahead` initializes in 16 of 20 and reaches $K=15$. On the 12 configurations where both initialize, divergences fall from 20,842 to 993, median minimum ESS rises from 6,447 to 7,876, and median ESS per 1,000 gradients rises from 84.3 to 152.4. It still fails under default random initialization at $K=25$: enforcing every local $3\\times3$ condition is necessary, but for $K\\ge4$ it is not sufficient for a globally feasible completion satisfying all remaining zero constraints.\n\n## 7. How Far Can $3\\times3$ Look-Ahead Propagate?\n\nThe gist implementation already has maximum *breadth*: at each C-vine pair $(i,j)$ it checks every future $k>j$, not only $k=j+1$. What it does not do is repeatedly propagate every narrowing through other triangles. A bound narrowed in one triangle can narrow another edge in a second triangle, which can then feed a third. To test that depth, I added an experimental transform that sweeps all currently active triples symmetrically for a fixed number of passes before each sequential coordinate. Each synchronous pass reads the previous pass's intervals, intersects all three projected edges, and never moves an equality or an already sampled coordinate.\n\nThe bounds still depend only on earlier raw coordinates and unsampled boxes. The transformation remains triangular, so the Jacobian needs only the current interval width, logistic derivative, and the existing C-vine scale factor; there is no additional \"projection Jacobian.\" Fixed pass counts also avoid a tolerance-dependent stopping rule inside HMC.\n\nThe next table uses the same five $K=7$, $\\eta=4$ patterns and sampler settings. Spans 1 through 5 limit both the pre-selection intersection and post-selection tightening to that many future indices. `all` reaches the maximum possible distance of 6 and is `cvine_lookahead`. The sweep rows retain all-future breadth and add synchronous all-triple propagation before every coordinate. For `rowscale`, pass 0 and pass 1 are the same executable with propagation disabled or enabled, which controls for floating-point changes between Stan programs.\n\n| experiment | total divergences | median min ESS | median ESS / 1k gradients | total time (s) |\n|:--------------------------|------------------:|---------------:|---------------------------:|---------------:|\n| C-vine, span 1 | 206 | 11,153 | 214.5 | 3.80 |\n| C-vine, span 2 | 43 | 10,562 | 205.7 | 3.06 |\n| C-vine, span 3 | 9 | 10,454 | 194.1 | 2.93 |\n| C-vine, span 4 | **8** | 10,454 | 194.1 | **2.84** |\n| C-vine, span 5 | **8** | 10,454 | 194.1 | 3.05 |\n| C-vine, all future $k$ | **8** | 10,454 | 194.1 | 2.99 |\n| C-vine, all + 1 sweep | **7** | **11,255** | **219.4** | 19.89 |\n| C-vine, all + 2 sweeps | **7** | **11,255** | **219.4** | 37.96 |\n| C-vine, all + 4 sweeps | **7** | **11,255** | **219.4** | 74.42 |\n| `rowscale`, 0 sweeps | 362 | 9,567 | 174.8 | **4.54** |\n| `rowscale`, 1 sweep | **207** | **10,334** | **188.6** | 9.11 |\n| `rowscale`, 2 sweeps | **207** | **10,334** | **188.6** | 16.67 |\n| `rowscale`, 4 sweeps | **207** | **10,334** | **188.6** | 31.39 |\n\nBreadth is the useful part for the C-vine: nearest-neighbor look-ahead leaves 206 divergences, two-step leaves 43, three-step leaves 9, and spans 4, 5, and all future indices agree at 8. One synchronous all-triple pass before each coordinate changes the C-vine path slightly and removes one more divergence, but costs nearly seven times as much; passes 2 and 4 produce exactly the same diagnostics and ESS as pass 1 while only multiplying run time. The naive repeated sweep is $O(pK^5)$ for $p$ passes, so it is an experiment rather than a recommended default.\n\nThe projection also transfers to an entry-wise Cholesky transform, provided it is applied to ordinary correlations rather than to Cholesky entries. For `rowscale`, I maintain boxes for $\\Omega_{ij}$, sweep all same-row pairs before each coordinate against the already known $\\Omega_{jk}$, then map the contracted interval back through $\\Omega_{ij}=b_1+L_{ij}L_{jj}$. One pass cuts divergences from 362 to 207 and improves median efficiency; additional passes saturate immediately. It helps, but unlike the subspace construction it does not remove the nonlocal constrained-completion boundary.\n\nI then ported the same one-pass ordinary-correlation sweep to six entry-wise transforms from the bake-off. At a common parity-check point, pass-zero mode reproduced each original log density and full raw-gradient vector to printed precision. The table compares pass zero with pass one in those same executables; this is a cleaner intervention than comparing separately compiled programs. The contraction happens on $\\Omega$, after which each transform retains its existing Cholesky or $LDL'$ scale and equality Jacobians.\n\n| model | successful patterns, 0 $\\to$ 1 pass | divergences, 0 $\\to$ 1 pass | median ESS / 1k gradients, 0 $\\to$ 1 pass |\n|:----------|:-------------------------------:|-----------------------------:|-------------------------------------------:|\n| `carpenter` | 5 $\\to$ 5 | 398 $\\to$ **195** | 199.3 $\\to$ **202.6** |\n| `pinkney` | 5 $\\to$ 5 | 395 $\\to$ **322** | 192.3 $\\to$ **199.1** |\n| `ldl2` | 5 $\\to$ 5 | 389 $\\to$ **275** | 187.7 $\\to$ **190.3** |\n| `ldl3` | 5 $\\to$ 5 | 370 $\\to$ **230** | 182.1 $\\to$ **190.9** |\n| `rowscale` | 5 $\\to$ 5 | 362 $\\to$ **207** | 174.8 $\\to$ **188.6** |\n| `schur` | 4 $\\to$ **5** | 224 $\\to$ **193**[^schur-lookahead] | 191.9 $\\to$ **202.2** |\n\n[^schur-lookahead]: The pass-zero `schur` fit failed during initialization for seed 5, while the one-pass transform initialized all four chains. Its divergence and efficiency comparison therefore uses the four patterns that succeeded under both settings.\n\nAcross the 29 matched model-pattern pairs, one sweep reduces divergences from 2,138 to 1,422, raises median minimum ESS from 10,222 to 10,334, and raises median ESS per 1,000 gradients from 189.7 to 190.9. Wall time doubles from 25.9 to 52.1 seconds. The direction is favorable for every model in aggregate, but the gain is much smaller than for `cvine_lookahead`, and individual fits can move the other way because HMC trajectories are chaotic near the boundary. Local $3\\times3$ pruning is therefore useful as a guardrail for the entry-wise family, not a replacement for a parameterization that is feasible by construction.\n\nOn a held-out $K=5$ pattern, the six one-pass posteriors also agree with the `carpenter` baseline: the largest free-cell mean difference is 0.016, the largest difference is 2.85 combined Monte Carlo standard errors, and the constrained cells remain zero to about $10^{-19}$. The experimental Stan sources, benchmark scripts, and raw result CSVs are stored alongside this post.\n\n## 8. Does It Hold Up? Scaling K and $\\eta$\n\nI next repeat the comparison for $K\\in\\{5,7,9,15,25\\}$ and $\\eta\\in\\{1,2,3,4\\}$. This sweep includes five entry-wise models, both C-vine models, `qr2`, `tri`, and the donut model with $m=6$. For each $K$, I generate one Bernoulli(0.5) zero pattern and reuse it for all four values of $\\eta$. The realized number of zeros ranges from 6 of 10 cells at $K=5$ to 143 of 300 at $K=25$. Sampler settings are unchanged. There is one fit per configuration, so small differences should be interpreted with the variability from Section 2 in mind.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(tidyr)\n\nsource(\"../../R/theme_blog.R\")\n\nsweep <- read.csv(\"sweep-results.csv\") |>\n  mutate(\n    family = case_when(\n      model == \"tri\" ~ \"Subspace (triangular basis)\",\n      model == \"qr2\" ~ \"Subspace (QR basis)\",\n      model == \"donut\" ~ \"Subspace (donut)\",\n      model == \"cvine_lookahead\" ~ \"C-vine (look-ahead)\",\n      .default = \"Forced zeros\"\n    ),\n    div_pct = 100 * divergences / 8000,\n    eta_lab = factor(paste0(\"eta == \", eta),\n                     levels = paste0(\"eta == \", sort(unique(eta))))\n  )\n\nfam_colors <- c(\n  \"Forced zeros\" = blog_colors$gold,\n  \"C-vine (look-ahead)\" = blog_colors$red,\n  \"Subspace (QR basis)\" = blog_colors$purple,\n  \"Subspace (donut)\" = blog_colors$blue,\n  \"Subspace (triangular basis)\" = blog_colors$teal\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sweep |> filter(!failed),\n       aes(x = K, y = div_pct, group = model, color = family)) +\n  geom_line(aes(linewidth = family, alpha = family, linetype = family)) +\n  geom_point(size = 1.6) +\n  facet_wrap(~eta_lab, nrow = 1, labeller = label_parsed) +\n  scale_color_manual(values = fam_colors, name = NULL) +\n  scale_linewidth_manual(guide = \"none\", values = c(\n    \"Forced zeros\" = 0.6, \"C-vine (look-ahead)\" = 0.9, \"Subspace (QR basis)\" = 1.1,\n    \"Subspace (donut)\" = 1.1, \"Subspace (triangular basis)\" = 1.3)) +\n  scale_alpha_manual(guide = \"none\", values = c(\n    \"Forced zeros\" = 0.65, \"C-vine (look-ahead)\" = 1, \"Subspace (QR basis)\" = 1,\n    \"Subspace (donut)\" = 1, \"Subspace (triangular basis)\" = 1)) +\n  scale_linetype_manual(guide = \"none\", values = c(\n    \"Forced zeros\" = \"solid\", \"C-vine (look-ahead)\" = \"solid\", \"Subspace (QR basis)\" = \"solid\",\n    \"Subspace (donut)\" = \"22\", \"Subspace (triangular basis)\" = \"solid\")) +\n  scale_x_continuous(breaks = c(5, 7, 9, 15, 25)) +\n  theme_blog() +\n  labs(\n    x = \"K (matrix dimension)\",\n    y = \"Divergent transitions (%)\",\n    title = \"Divergence Rate by Matrix Dimension\",\n    subtitle = \"One Bernoulli(0.5) zero pattern per K and 8,000 post-warmup transitions per fit\"\n  ) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Divergence rate by matrix dimension and LKJ concentration. Thin gold lines are the original sequential transforms and the red line is cvine_lookahead; missing points indicate initialization failures. The tri model has zero divergences in every panel. For qr2 at K = 15 and eta = 2, one chain has 100% divergences. The donut model remains below 1.5% throughout.](corr-zeros-bakeoff_files/figure-html/fig-divergence-scaling-1.png){#fig-divergence-scaling width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sweep |> filter(!failed),\n       aes(x = K, y = ess_per_1k_grad, group = model, color = family)) +\n  geom_line(aes(linewidth = family, alpha = family, linetype = family)) +\n  geom_point(size = 1.6) +\n  facet_wrap(~eta_lab, nrow = 1, labeller = label_parsed) +\n  scale_color_manual(values = fam_colors, name = NULL) +\n  scale_linewidth_manual(guide = \"none\", values = c(\n    \"Forced zeros\" = 0.6, \"C-vine (look-ahead)\" = 0.9, \"Subspace (QR basis)\" = 1.1,\n    \"Subspace (donut)\" = 1.1, \"Subspace (triangular basis)\" = 1.3)) +\n  scale_alpha_manual(guide = \"none\", values = c(\n    \"Forced zeros\" = 0.65, \"C-vine (look-ahead)\" = 1, \"Subspace (QR basis)\" = 1,\n    \"Subspace (donut)\" = 1, \"Subspace (triangular basis)\" = 1)) +\n  scale_linetype_manual(guide = \"none\", values = c(\n    \"Forced zeros\" = \"solid\", \"C-vine (look-ahead)\" = \"solid\", \"Subspace (QR basis)\" = \"solid\",\n    \"Subspace (donut)\" = \"22\", \"Subspace (triangular basis)\" = \"solid\")) +\n  scale_x_continuous(breaks = c(5, 7, 9, 15, 25)) +\n  scale_y_log10() +\n  theme_blog() +\n  labs(\n    x = \"K (matrix dimension)\",\n    y = \"min ESS per 1,000 gradients (log)\",\n    title = \"Sampling Efficiency by Matrix Dimension\",\n    subtitle = \"Higher is better; missing points indicate initialization failures\"\n  ) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Sampling efficiency (min bulk ESS over free correlations per 1,000 gradient evaluations, log scale) by dimension and concentration.](corr-zeros-bakeoff_files/figure-html/fig-efficiency-scaling-1.png){#fig-efficiency-scaling width=100%}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Outright failures: initialization could not find a feasible point after 100 attempts per chain.\n\n|model           |K = 25      |K = 15      |K = 7       |K = 9       |\n|:---------------|:-----------|:-----------|:-----------|:-----------|\n|carpenter       |4 of 4 etas |—           |—           |—           |\n|cvine           |4 of 4 etas |4 of 4 etas |—           |—           |\n|cvine_lookahead |4 of 4 etas |—           |—           |—           |\n|ldl2            |4 of 4 etas |—           |—           |—           |\n|ldl3            |4 of 4 etas |—           |—           |—           |\n|pinkney         |4 of 4 etas |—           |—           |—           |\n|schur           |4 of 4 etas |4 of 4 etas |4 of 4 etas |4 of 4 etas |\n\n\n:::\n:::\n\n\nAt $\\eta=1$, the entry-wise models have 15--18% divergences for $K=5$ and 85--94% for $K=7$ and $K=9$. The uniform LKJ prior places more mass near the part of the parameter space where a solved Cholesky entry can exceed the remaining row norm. Four curves coincide in the $\\eta=1$ panel because `carpenter`, `pinkney`, `ldl2`, and `ldl3` have the same density in their raw coordinates until floating-point differences separate their trajectories.\n\nInitialization also becomes difficult for the sequential models. For these particular patterns, `schur` fails to initialize from $K=7$ onward and `cvine` fails from $K=15$ onward. The `cvine_lookahead` model initializes and samples through $K=15$, but still fails to find a feasible default initialization at $K=25$. The other entry-wise models also fail at $K=25$. This depends on the zero pattern—`schur` initialized for every pattern in Section 5—but the problem becomes more likely as the number of constraints increases. Every initial value in the subspace models satisfies the zero constraints by construction.\n\nThe `tri` model has zero divergences in all 20 configurations. The donut model remains below 1.5% divergences throughout, with small counts for $\\eta\\le2$ and none for $\\eta\\ge3$. Through $K=15$, the minimum bulk ESS for `tri` remains near the number of posterior draws. At $K=25$, the minimum is taken over 157 free correlations and ranges from about 5,100 to 6,600 for `tri`. The donut model ranges from about 4,700 to 6,600. Both complete in seconds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsub_tab <- sweep |>\n  filter(model %in% c(\"tri\", \"donut\")) |>\n  mutate(cell = sprintf(\"%s (%s)%s\",\n                        format(round(min_ess), big.mark = \",\"),\n                        round(ess_per_1k_grad),\n                        ifelse(divergences > 0,\n                               paste0(\" [\", divergences, \" div]\"), \"\")))\n\nsub_wide <- sub_tab |>\n  select(model, K, N_zero, eta, cell) |>\n  pivot_wider(names_from = eta, values_from = cell,\n              names_prefix = \"eta = \") |>\n  left_join(\n    sub_tab |>\n      group_by(model, K) |>\n      summarize(`wall clock (s)` = sprintf(\"%.1f-%.1f\",\n                                           min(seconds), max(seconds)),\n                .groups = \"drop\"),\n    by = c(\"model\", \"K\")\n  ) |>\n  mutate(`zero / free cells` = paste0(N_zero, \" / \", choose(K, 2) - N_zero),\n         .after = K) |>\n  select(-N_zero) |>\n  arrange(K, desc(model))\n\nknitr::kable(\n  sub_wide, align = c(\"l\", \"r\", \"c\", rep(\"c\", 4), \"c\"),\n  caption = \"tri and the donut (m_radius = 6) across the full sweep: min bulk ESS of 8,000 draws (ESS per 1,000 gradients in parentheses; divergent transitions in brackets where nonzero -- tri has none anywhere). Wall clock is the range across eta for 4 parallel chains.\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: tri and the donut (m_radius = 6) across the full sweep: min bulk ESS of 8,000 draws (ESS per 1,000 gradients in parentheses; divergent transitions in brackets where nonzero -- tri has none anywhere). Wall clock is the range across eta for 4 parallel chains.\n\n|model |  K| zero / free cells |       eta = 1       |      eta = 2       |   eta = 3    |   eta = 4    | wall clock (s) |\n|:-----|--:|:-----------------:|:-------------------:|:------------------:|:------------:|:------------:|:--------------:|\n|tri   |  5|       6 / 4       |     6,839 (127)     |    8,619 (183)     | 8,129 (192)  | 8,530 (204)  |    0.1-0.3     |\n|donut |  5|       6 / 4       | 2,364 (20) [23 div] |     3,865 (66)     | 6,715 (120)  | 8,832 (172)  |    0.3-0.5     |\n|tri   |  7|      7 / 14       |     6,922 (87)      |    7,572 (134)     | 10,480 (188) | 10,832 (196) |    0.4-0.5     |\n|donut |  7|      7 / 14       | 2,031 (19) [42 div] |     5,796 (70)     | 7,128 (117)  | 8,430 (151)  |    0.5-0.8     |\n|tri   |  9|      13 / 23      |     6,419 (87)      |    6,707 (118)     | 7,424 (132)  | 8,221 (147)  |    0.6-0.7     |\n|donut |  9|      13 / 23      | 5,315 (36) [54 div] | 5,969 (74) [1 div] | 6,977 (123)  | 6,834 (120)  |    0.7-1.5     |\n|tri   | 15|      64 / 41      |     7,298 (67)      |    7,836 (134)     | 7,761 (127)  | 8,340 (149)  |    1.3-2.0     |\n|donut | 15|      64 / 41      | 5,046 (41) [99 div] |     7,532 (79)     |  6,515 (82)  | 7,523 (122)  |    1.8-3.1     |\n|tri   | 25|     143 / 157     |     5,081 (42)      |     5,837 (51)     |  5,742 (50)  |  6,553 (55)  |    7.0-8.9     |\n|donut | 25|     143 / 157     | 4,667 (29) [98 div] | 5,547 (46) [2 div] |  5,524 (46)  |  5,907 (50)  |    9.3-14.4    |\n\n\n:::\n:::\n\n\nThe QR basis remains feasible when the entry-wise models fail, but it becomes expensive as $K$ grows. At $K=25$, $\\eta=1$, `qr2` takes 852 seconds compared with 8.9 seconds for `tri`. At $K=15$, $\\eta=2$, one `qr2` chain has 100% divergences and the minimum ESS is 7. The `ldl3` model has a similar isolated failure at $K=9$, $\\eta=2$, with a minimum ESS of 19. At $K=25$, the minimum ESS for `qr2` is about 3,500--4,100, compared with 5,100--6,600 for `tri`, and `qr2` requires many more gradient evaluations. `tri` has the highest ESS per gradient in 14 of the 20 configurations, `cvine_lookahead` in four, and `qr2` in two.\n\n## 9. When to Use Which\n\n| Scenario | Recommendation |\n|:-----------------------------------|:-----------------------------------|\n| Structural zeros only | Use `tri` |\n| Structural zeros at very large $K$ | Use `tri`, but profile the per-row $d\\times d$ Cholesky factorizations |\n| Zeros plus other known correlation values | Use the entry-wise method [@pinkney2024; @pinkneytalk]; `tri` currently handles zeros only |\n| Zeros plus bounds on other correlations | Use the entry-wise method, which already supports bounded transforms [@pinkney2024; @pinkneytalk] |\n\nFor structural zeros alone, I do not see a reason to prefer one of the entry-wise parameterizations. In these benchmarks `tri` is more reliable and at least as efficient. The entry-wise method remains the established option here for more general constraints. The underlying look-ahead C-vine also accepts nonzero equalities and bounded free correlations, but this zeros-only adapter does not benchmark those cases.\n\n## 10. Discussion\n\nThe entry-wise construction solves each zero constraint but leaves the boundary of the feasible row norm in the parameter space. This produces divergences for the smaller examples and initialization failures for the larger ones. `cvine_lookahead` narrows sequential partial-correlation intervals using exact $3\\times3$ feasibility projections and performs much better, but dense patterns can still leave a nonlocal constrained-completion boundary. The subspace construction removes that boundary because every parameter value maps to a row satisfying the constraints.\n\nThe choice of basis is important. A complement obtained directly from QR is valid, but its coordinates change with the earlier rows and sampling becomes less efficient. The triangular basis fixes the free coordinates to matrix entries and only solves for the constrained coordinates. In these benchmarks, that gives zero divergences without sacrificing effective sample size or run time.\n\nThere are two limitations I have not addressed here. The general look-ahead C-vine also supports nonzero equalities and bounded free correlations, but this bake-off's interface specializes it to exact zeros and does not compare those targets. Also, the small Cholesky factorization performed for each constrained row should be profiled for matrices with dimensions in the hundreds.\n\n## Acknowledgments\n\nThe exact-constraint subspace idea, zeros as orthogonality constraints with the sample lifted from a lower-dimensional hemisphere through the orthogonal complement, including the $\\det R$ Jacobian factor, is due to Seth Axen [@axen2023], whose radial prior [@axen2022] the donut variant relies on. The `tri` model is that idea with a canonical triangular choice of complement basis and the determinant factored analytically. Thanks to Bob Carpenter for the compact zeros-only formulation benchmarked here as `carpenter`, and for the Discourse conversation that prompted this bake-off. The C-vine construction rests on the vine and partial-correlation results of @joe2006 and @lewandowski2009.\n\n## Appendix: Stan Code for All Thirteen Parameterizations\n\n::: panel-tabset\n### tri\n\n``` {.stan filename=\"unitvec-stereo-corr-zeros.stan\"}\nfunctions {\n  matrix cholesky_corr_constrain_stereo_jacobian(int K, vector raw,\n                                              array[,] int zeros) {\n    // Exact-constraint subspace geometry but with a canonical\n    // triangular basis instead of Householder QR: basis vector k is a unit\n    // at free column k with the row's forced columns filled in by\n    // back-substitution through the zero constraints, then orthonormalized\n    // by the Cholesky factor of its small Gram matrix. The basis is\n    // anchored to matrix entries and varies smoothly with earlier rows.\n    matrix[K, K] L = rep_matrix(0, K, K);\n    int raw_idx = 1;\n    int zero_idx = 1;\n    L[1, 1] = 1;\n\n    for (i in 2:K) {\n      int n_z = 0;\n      while (zero_idx + n_z <= size(zeros)\n             && zeros[zero_idx + n_z, 1] == i) {\n        n_z += 1;\n      }\n      int d = i - 1 - n_z;\n\n      // subsphere coordinates via the modified stereographic chart:\n      // z = sqrt(t + 2) / (t + 1) * y with t = y'y, diagonal 1 / (t + 1)\n      vector[d] z;\n      real r = 1;\n      if (d > 0) {\n        vector[d] y = raw[raw_idx:(raw_idx + d - 1)];\n        real t = dot_self(y);\n        z = (sqrt(t + 2) / (t + 1)) * y;\n        r = 1 / (t + 1);\n        jacobian += 0.5 * (d - 2) * log(t + 2) - (d + 1) * log1p(t);\n        raw_idx += d;\n      }\n\n      if (n_z == 0) {\n        if (d > 0) {\n          L[i, 1:d] = z';\n        }\n        L[i, i] = r;\n      } else {\n        array[n_z] int zc;\n        for (m in 1:n_z) {\n          zc[m] = zeros[zero_idx + m - 1, 2];\n        }\n\n        // the joint-delta term -0.5 * log det(Gram of zero-partner rows)\n        // factors: splitting the partner matrix A by forced/free coords,\n        // A_Z is triangular with the partners' diagonals, and by Sylvester\n        // det(A'A) = prod(L[j,j])^2 * det(T'T)\n        for (m in 1:n_z) {\n          jacobian += -log(L[zc[m], zc[m]]);\n        }\n\n        if (d > 0) {\n          array[d] int free_cols;\n          {\n            int fc = 0;\n            int zp = 1;\n            for (c in 1:(i - 1)) {\n              if (zp <= n_z && zc[zp] == c) {\n                zp += 1;\n              } else {\n                fc += 1;\n                free_cols[fc] = c;\n              }\n            }\n          }\n          // triangular basis: unit at each free column, forced columns\n          // filled by back-substitution so every column is orthogonal to\n          // the zero-partner rows\n          matrix[i - 1, d] T = rep_matrix(0, i - 1, d);\n          for (k in 1:d) {\n            int col = free_cols[k];\n            T[col, k] = 1;\n            for (m in 1:n_z) {\n              int j = zc[m];\n              if (j > col) {\n                T[j, k] = -dot_product(L[j, 1:(j - 1)], T[1:(j - 1), k])\n                          / L[j, j];\n              }\n            }\n          }\n          // T's free-column rows are the identity, so T'T = I + W'W with\n          // W the forced-column rows only\n          matrix[n_z, d] W;\n          for (m in 1:n_z) {\n            W[m, ] = T[zc[m], ];\n          }\n          // orthonormalize: v = T * S'^{-1} * z has ||v|| = ||z||;\n          // diagonal(S) doubles as the det(T'T) half of the delta term\n          matrix[d, d] S = cholesky_decompose(add_diag(crossprod(W), 1.0));\n          jacobian += -sum(log(diagonal(S)));\n          vector[d] t = mdivide_right_tri_low(z', S)';\n          L[i, 1:(i - 1)] = (T * t)';\n        }\n        L[i, i] = r;\n        zero_idx += n_z;\n      }\n    }\n    return L;\n  }\n}\ndata {\n  int<lower=2> K;                             // dimension of correlation matrix\n  real<lower=0> eta;                          // concentration in LKJ Cholesky\n  int<lower=0, upper=choose(K, 2)> N_zero;    // # structural zero correlations\n  array[N_zero, 2] int zeros;                 // lower triangular, row major order\n}\nparameters {\n  vector[choose(K, 2) - N_zero] raw;\n}\ntransformed parameters {\n  matrix[K, K] L_Omega = cholesky_corr_constrain_stereo_jacobian(K, raw, zeros);\n}\nmodel {\n  L_Omega ~ lkj_corr_cholesky(eta);\n}\ngenerated quantities {\n  matrix[K, K] Omega = multiply_lower_tri_self_transpose(L_Omega);\n}\n\n```\n\n### donut\n\n``` {.stan filename=\"unitvec-donut-corr-zeros.stan\"}\nfunctions {\n  matrix cholesky_corr_constrain_donut_jacobian(int K, vector raw,\n                                                array[,] int zeros,\n                                                real m_radius) {\n    // Exact-constraint subspace geometry with the triangular basis, but the\n    // subsphere is parameterized by normalizing a free vector (\"donut\"):\n    // one extra parameter per row, u = y / ||y||, with -0.5 * y'y keeping\n    // the radius Gaussian and independent of the direction. The diagonal\n    // is |u_last| (the two mirror hemispheres fold onto the same L), and\n    // the measure conversion dz = |u_last| dsigma contributes log|u_last|\n    // on top of the LKJ weight supplied by the model block.\n    matrix[K, K] L = rep_matrix(0, K, K);\n    int raw_idx = 1;\n    int zero_idx = 1;\n    L[1, 1] = 1;\n\n    for (i in 2:K) {\n      int n_z = 0;\n      while (zero_idx + n_z <= size(zeros)\n             && zeros[zero_idx + n_z, 1] == i) {\n        n_z += 1;\n      }\n      int d = i - 1 - n_z;\n\n      vector[d + 1] y = raw[raw_idx:(raw_idx + d)];\n      real s = norm2(y);\n      vector[d + 1] u = y / s;\n      // radial prior centered at m_radius repels the norm from the\n      // origin singularity of the normalization (Axen, \"A better unit\n      // vector\", Stan Discourse post 30); m_radius = 0 recovers the\n      // implicit chi-distributed radius. The direction marginal, and\n      // hence the Omega posterior, is unchanged.\n      jacobian += -0.5 * square(s - m_radius) + log(abs(u[d + 1]));\n      L[i, i] = abs(u[d + 1]);\n      raw_idx += d + 1;\n\n      if (n_z == 0) {\n        if (d > 0) {\n          L[i, 1:d] = u[1:d]';\n        }\n      } else {\n        array[n_z] int zc;\n        for (m in 1:n_z) {\n          zc[m] = zeros[zero_idx + m - 1, 2];\n        }\n\n        // -0.5 * log det(Gram of zero-partner rows) from the joint delta\n        matrix[i - 1, n_z] A;\n        for (m in 1:n_z) {\n          A[, m] = L[zc[m], 1:(i - 1)]';\n        }\n        jacobian += -sum(log(diagonal(cholesky_decompose(crossprod(A)))));\n\n        if (d > 0) {\n          array[d] int free_cols;\n          {\n            int fc = 0;\n            int zp = 1;\n            for (c in 1:(i - 1)) {\n              if (zp <= n_z && zc[zp] == c) {\n                zp += 1;\n              } else {\n                fc += 1;\n                free_cols[fc] = c;\n              }\n            }\n          }\n          // triangular basis: unit at each free column, forced columns\n          // filled by back-substitution so every column is orthogonal to\n          // the zero-partner rows\n          matrix[i - 1, d] T = rep_matrix(0, i - 1, d);\n          for (k in 1:d) {\n            int col = free_cols[k];\n            T[col, k] = 1;\n            for (m in 1:n_z) {\n              int j = zc[m];\n              if (j > col) {\n                T[j, k] = -dot_product(L[j, 1:(j - 1)], T[1:(j - 1), k])\n                          / L[j, j];\n              }\n            }\n          }\n          // orthonormalize: v = T * S'^{-1} * u[1:d] has ||v|| = ||u[1:d]||\n          matrix[d, d] S = cholesky_decompose(crossprod(T));\n          vector[d] t = mdivide_right_tri_low(u[1:d]', S)';\n          L[i, 1:(i - 1)] = (T * t)';\n        }\n        zero_idx += n_z;\n      }\n    }\n    return L;\n  }\n}\ndata {\n  int<lower=2> K;                             // dimension of correlation matrix\n  real<lower=0> eta;                          // concentration in LKJ Cholesky\n  int<lower=0, upper=choose(K, 2)> N_zero;    // # structural zero correlations\n  array[N_zero, 2] int zeros;                 // lower triangular, row major order\n  real<lower=0> m_radius;                     // radial prior center; 0 = chi radius\n}\nparameters {\n  // one extra parameter per row: dim d + 1 per row sums to\n  // choose(K, 2) - N_zero + (K - 1)\n  vector[choose(K, 2) - N_zero + K - 1] raw;\n}\ntransformed parameters {\n  matrix[K, K] L_Omega = cholesky_corr_constrain_donut_jacobian(K, raw, zeros,\n                                                                m_radius);\n}\nmodel {\n  L_Omega ~ lkj_corr_cholesky(eta);\n}\ngenerated quantities {\n  matrix[K, K] Omega = multiply_lower_tri_self_transpose(L_Omega);\n}\n\n```\n\n### carpenter\n\n``` {.stan filename=\"carpenter-corr-zeros.stan\"}\nfunctions {\n  int is_zero(int row_idx, int col_idx, array[,] int zeros, int zero_idx) {\n    return zero_idx <= size(zeros)\n      && zeros[zero_idx, 1] == row_idx\n      && zeros[zero_idx, 2] == col_idx;\n  }\n  \n  matrix cholesky_corr_zeros_jacobian(int D,\n                                      vector raw,\n                                      array[,] int zeros) {\n    int raw_idx = 1;\n    int zero_idx = 1;\n    matrix[D, D] L = rep_matrix(0, D, D);\n    for (i in 1:D) {\n      real stick = 1;\n      for (j in 1:(i - 1)) {\n        if (is_zero(i, j, zeros, zero_idx)) {\n          real b = dot_product(L[j, 1:(j - 1)], L[i, 1:(j - 1)]);\n          L[i, j] = -b / L[j, j];  // implies Omega[i, j] == 0\n          zero_idx += 1;\n        } else {\n\t  real sqrt_stick = sqrt(stick);\n          L[i, j] = lower_upper_bound_jacobian(raw[raw_idx], -sqrt_stick, sqrt_stick);  // inside stick\n          raw_idx += 1;\n          jacobian += 0;\n        }\n\tstick -= L[i, j]^2;\n      }\n      L[i, i] = sqrt(stick);\n    }\n    return L;\n  }\n\n  real lkj_cholesky_corr_zeros_lpdf(matrix L,\n                                    real nu,\n                                    array[,] int zeros) {\n    real lp = lkj_corr_cholesky_lpdf(L | nu);  // over-adjusts\n    int N_zero = size(zeros);\n    for (n in 1:N_zero) {                      \n      int col_idx = zeros[n, 2];\n      lp -= log(L[col_idx, col_idx]);          // correct over-adjustment\n    }\n    return lp;\n  }\n}\ndata {\n  int<lower=2> D;                             // dimension of correlation matrix\n  real<lower=0> eta;                          // concentration in LKJ Cholesky\n  int<lower=0, upper=choose(D, 2)> N_zero;    // # structural zero correlations\n  array[N_zero, 2] int zeros;                 // lower triangular, row major order\n}\nparameters {\n  vector[choose(D, 2) - N_zero] raw;           // raw parameters\n}\ntransformed parameters {\n  matrix[D, D] L_Omega = cholesky_corr_zeros_jacobian(D, raw, zeros);\n}\nmodel {\n  L_Omega ~ lkj_cholesky_corr_zeros(eta, zeros);\n}\ngenerated quantities {\n  matrix[D, D] Omega = multiply_lower_tri_self_transpose(L_Omega);\n}\n\n```\n\n### pinkney\n\n``` {.stan filename=\"pinkney-corr-zeros2.stan\"}\nfunctions {\n  int is_zero(int row_idx, int col_idx, array[,] int zeros, int zero_idx) {\n    return zero_idx <= size(zeros)\n      && zeros[zero_idx, 1] == row_idx\n      && zeros[zero_idx, 2] == col_idx;\n  }\n\n  matrix cholesky_corr_constrain_outer_jacobian(int K, vector raw,\n                                                array[,] int zeros) {\n    matrix[K, K] L = rep_matrix(0, K, K);\n    int raw_idx = 1;\n    int zero_idx = 1;\n    L[1, 1] = 1;\n\n    for (i in 2:K) {\n      // remaining radius of row i: sqrt(1 - sum of squares so far)\n      real l_ij_old = 1;\n      for (j in 1:(i - 1)) {\n        real l_ij_old_x_l_jj = l_ij_old * L[j, j];\n        real b1 = dot_product(L[j, 1:(j - 1)], L[i, 1:(j - 1)]);\n        // how to derive the bounds\n        // we know that the correlation value C is bound by\n        // b1 - Ljj * Lij_old <= C <= b1 + Ljj * Lij_old\n        // Now we want our bounds to be enforced too so\n        // max(lb, b1 - Ljj * Lij_old) <= C <= min(ub, b1 + Ljj * Lij_old)\n        // We have Lij_new = (C - b1) / Ljj\n        real x;\n        if (is_zero(i, j, zeros, zero_idx)) {\n          x = -b1;  // Omega[i, j] = b1 + Lij * Ljj = 0\n          zero_idx += 1;\n        } else {\n          real low = max({-l_ij_old_x_l_jj, -1 - b1});\n          real up = min({l_ij_old_x_l_jj, 1 - b1});\n          x = lower_upper_bound_jacobian(raw[raw_idx], low, up);\n          raw_idx += 1;\n        }\n        L[i, j] = x / L[j, j];\n        // free entries: change of variables x -> L[i, j]\n        // zero entries: Carpenter's correction for the LKJ over-adjustment\n        jacobian += -log(L[j, j]);\n        l_ij_old *= sqrt(1 - (L[i, j] / l_ij_old)^2);\n      }\n      L[i, i] = l_ij_old;\n    }\n    return L;\n  }\n}\ndata {\n  int<lower=2> K;                             // dimension of correlation matrix\n  real<lower=0> eta;                          // concentration in LKJ Cholesky\n  int<lower=0, upper=choose(K, 2)> N_zero;    // # structural zero correlations\n  array[N_zero, 2] int zeros;                 // lower triangular, row major order\n}\nparameters {\n  vector[choose(K, 2) - N_zero] raw;\n}\ntransformed parameters {\n  matrix[K, K] L_Omega = cholesky_corr_constrain_outer_jacobian(K, raw, zeros);\n}\nmodel {\n  L_Omega ~ lkj_corr_cholesky(eta);\n}\ngenerated quantities {\n  matrix[K, K] Omega = multiply_lower_tri_self_transpose(L_Omega);\n}\n\n```\n\n### ldl\n\n``` {.stan filename=\"pinkney-corr-zeros-ldl.stan\"}\nfunctions {\n  int is_zero(int row_idx, int col_idx, array[,] int zeros, int zero_idx) {\n    return zero_idx <= size(zeros)\n      && zeros[zero_idx, 1] == row_idx\n      && zeros[zero_idx, 2] == col_idx;\n  }\n\n  matrix cholesky_corr_constrain_ldl_jacobian(int K, vector raw,\n                                              array[,] int zeros) {\n    // Omega = L * diag(D) * L' with unit lower-triangular L;\n    // the Cholesky factor is diag_post_multiply(L, sqrt(D))\n    matrix[K, K] L = diag_matrix(rep_vector(1, K));\n    vector[K] D;\n    vector[K] log_D;\n    int raw_idx = 1;\n    int zero_idx = 1;\n    D[1] = 1;\n    log_D[1] = 0;\n\n    for (i in 2:K) {\n      // log remaining radius^2 of row i: log(1 - sum_{k<j} L[i,k]^2 * D[k])\n      real log_r = 0;\n      for (j in 1:(i - 1)) {\n        real b1 = dot_product(D[1:(j - 1)]' .* L[j, 1:(j - 1)],\n                              L[i, 1:(j - 1)]);\n        // Omega[i, j] = b1 + L[i, j] * D[j] and the correlation C satisfies\n        // |C - b1| <= sqrt(D[j] * r), intersected with (-1, 1)\n        real x;\n        if (is_zero(i, j, zeros, zero_idx)) {\n          x = -b1;  // Omega[i, j] = b1 + Lij * Dj = 0\n          zero_idx += 1;\n        } else {\n          real b2 = exp(0.5 * (log_r + log_D[j]));\n          real low = max({-b2, -1 - b1});\n          real up = min({b2, 1 - b1});\n          x = lower_upper_bound_jacobian(raw[raw_idx], low, up);\n          raw_idx += 1;\n        }\n        L[i, j] = x / D[j];\n        // free entries: change of variables x -> L_chol[i, j] = x / sqrt(D[j])\n        // zero entries: Carpenter's correction -log(L_chol[j, j])\n        jacobian += -0.5 * log_D[j];\n        log_r = log_diff_exp(log_r, log_D[j] + 2 * log(abs(L[i, j])));\n      }\n      log_D[i] = log_r;\n      D[i] = exp(log_r);\n    }\n    return diag_post_multiply(L, sqrt(D));\n  }\n}\ndata {\n  int<lower=2> K;                             // dimension of correlation matrix\n  real<lower=0> eta;                          // concentration in LKJ Cholesky\n  int<lower=0, upper=choose(K, 2)> N_zero;    // # structural zero correlations\n  array[N_zero, 2] int zeros;                 // lower triangular, row major order\n}\nparameters {\n  vector[choose(K, 2) - N_zero] raw;\n}\ntransformed parameters {\n  matrix[K, K] L_Omega = cholesky_corr_constrain_ldl_jacobian(K, raw, zeros);\n}\nmodel {\n  L_Omega ~ lkj_corr_cholesky(eta);\n}\ngenerated quantities {\n  matrix[K, K] Omega = multiply_lower_tri_self_transpose(L_Omega);\n}\n\n```\n\n### ldl2\n\n``` {.stan filename=\"pinkney-corr-zeros-ldl2.stan\"}\nfunctions {\n  int is_zero(int row_idx, int col_idx, array[,] int zeros, int zero_idx) {\n    return zero_idx <= size(zeros)\n      && zeros[zero_idx, 1] == row_idx\n      && zeros[zero_idx, 2] == col_idx;\n  }\n\n  matrix cholesky_corr_constrain_ldl2_jacobian(int K, vector raw,\n                                               array[,] int zeros) {\n    // Omega = L * diag(D) * L' with unit lower-triangular L;\n    // the Cholesky factor is diag_post_multiply(L, sqrt(D)).\n    // Same as ldl version except the remaining radius is updated with\n    // log1m of the ratio instead of log_diff_exp.\n    matrix[K, K] L = diag_matrix(rep_vector(1, K));\n    vector[K] D;\n    vector[K] log_D;\n    int raw_idx = 1;\n    int zero_idx = 1;\n    D[1] = 1;\n    log_D[1] = 0;\n\n    for (i in 2:K) {\n      // log remaining radius^2 of row i: log(1 - sum_{k<j} L[i,k]^2 * D[k])\n      real log_r = 0;\n      for (j in 1:(i - 1)) {\n        real b1 = dot_product(D[1:(j - 1)]' .* L[j, 1:(j - 1)],\n                              L[i, 1:(j - 1)]);\n        // Omega[i, j] = b1 + L[i, j] * D[j] and the correlation C satisfies\n        // |C - b1| <= sqrt(D[j] * r), intersected with (-1, 1)\n        real x;\n        if (is_zero(i, j, zeros, zero_idx)) {\n          x = -b1;  // Omega[i, j] = b1 + Lij * Dj = 0\n          zero_idx += 1;\n        } else {\n          real b2 = exp(0.5 * (log_r + log_D[j]));\n          real low = max({-b2, -1 - b1});\n          real up = min({b2, 1 - b1});\n          x = lower_upper_bound_jacobian(raw[raw_idx], low, up);\n          raw_idx += 1;\n        }\n        L[i, j] = x / D[j];\n        // free entries: change of variables x -> L_chol[i, j] = x / sqrt(D[j])\n        // zero entries: Carpenter's correction -log(L_chol[j, j])\n        jacobian += -0.5 * log_D[j];\n        log_r += log1m(D[j] * L[i, j]^2 / exp(log_r));\n      }\n      log_D[i] = log_r;\n      D[i] = exp(log_r);\n    }\n    return diag_post_multiply(L, sqrt(D));\n  }\n}\ndata {\n  int<lower=2> K;                             // dimension of correlation matrix\n  real<lower=0> eta;                          // concentration in LKJ Cholesky\n  int<lower=0, upper=choose(K, 2)> N_zero;    // # structural zero correlations\n  array[N_zero, 2] int zeros;                 // lower triangular, row major order\n}\nparameters {\n  vector[choose(K, 2) - N_zero] raw;\n}\ntransformed parameters {\n  matrix[K, K] L_Omega = cholesky_corr_constrain_ldl2_jacobian(K, raw, zeros);\n}\nmodel {\n  L_Omega ~ lkj_corr_cholesky(eta);\n}\ngenerated quantities {\n  matrix[K, K] Omega = multiply_lower_tri_self_transpose(L_Omega);\n}\n\n```\n\n### ldl3\n\n``` {.stan filename=\"pinkney-corr-zeros-ldl3.stan\"}\nfunctions {\n  int is_zero(int row_idx, int col_idx, array[,] int zeros, int zero_idx) {\n    return zero_idx <= size(zeros)\n      && zeros[zero_idx, 1] == row_idx\n      && zeros[zero_idx, 2] == col_idx;\n  }\n\n  matrix cholesky_corr_constrain_ldl3_jacobian(int K, vector raw,\n                                               array[,] int zeros) {\n    // Omega = L * diag(D) * L' with unit lower-triangular L;\n    // the Cholesky factor is diag_post_multiply(L, sqrt(D)).\n    // Same as the ldl versions except the remaining radius is tracked on\n    // the natural scale: r -= D[j] * L[i, j]^2.\n    matrix[K, K] L = diag_matrix(rep_vector(1, K));\n    vector[K] D;\n    int raw_idx = 1;\n    int zero_idx = 1;\n    D[1] = 1;\n\n    for (i in 2:K) {\n      // remaining radius^2 of row i: 1 - sum_{k<j} L[i,k]^2 * D[k]\n      real r = 1;\n      for (j in 1:(i - 1)) {\n        real b1 = dot_product(D[1:(j - 1)]' .* L[j, 1:(j - 1)],\n                              L[i, 1:(j - 1)]);\n        // Omega[i, j] = b1 + L[i, j] * D[j] and the correlation C satisfies\n        // |C - b1| <= sqrt(D[j] * r), intersected with (-1, 1)\n        real x;\n        if (is_zero(i, j, zeros, zero_idx)) {\n          x = -b1;  // Omega[i, j] = b1 + Lij * Dj = 0\n          zero_idx += 1;\n        } else {\n          real b2 = sqrt(r * D[j]);\n          real low = max({-b2, -1 - b1});\n          real up = min({b2, 1 - b1});\n          x = lower_upper_bound_jacobian(raw[raw_idx], low, up);\n          raw_idx += 1;\n        }\n        L[i, j] = x / D[j];\n        // free entries: change of variables x -> L_chol[i, j] = x / sqrt(D[j])\n        // zero entries: Carpenter's correction -log(L_chol[j, j])\n        jacobian += -0.5 * log(D[j]);\n        r -= D[j] * L[i, j]^2;\n      }\n      D[i] = r;\n    }\n    return diag_post_multiply(L, sqrt(D));\n  }\n}\ndata {\n  int<lower=2> K;                             // dimension of correlation matrix\n  real<lower=0> eta;                          // concentration in LKJ Cholesky\n  int<lower=0, upper=choose(K, 2)> N_zero;    // # structural zero correlations\n  array[N_zero, 2] int zeros;                 // lower triangular, row major order\n}\nparameters {\n  vector[choose(K, 2) - N_zero] raw;\n}\ntransformed parameters {\n  matrix[K, K] L_Omega = cholesky_corr_constrain_ldl3_jacobian(K, raw, zeros);\n}\nmodel {\n  L_Omega ~ lkj_corr_cholesky(eta);\n}\ngenerated quantities {\n  matrix[K, K] Omega = multiply_lower_tri_self_transpose(L_Omega);\n}\n\n```\n\n### cvine\n\n``` {.stan filename=\"cvine-corr-zeros.stan\"}\nfunctions {\n  // traversal here is tree-by-tree (column major), so scan instead of the\n  // merge-join used by the row-major models\n  int is_zero_scan(int row_idx, int col_idx, array[,] int zeros) {\n    for (n in 1:size(zeros)) {\n      if (zeros[n, 1] == row_idx && zeros[n, 2] == col_idx) {\n        return 1;\n      }\n    }\n    return 0;\n  }\n\n  matrix corr_constrain_cvine_jacobian(int K, vector raw,\n                                       array[,] int zeros, real eta) {\n    matrix[K, K] C = identity_matrix(K);\n    matrix[K, K] P = identity_matrix(K);\n    // LKJ in C-vine form: partial corr in tree i ~ Beta(a - i/2 adjustments);\n    // constant base a with the -0.5 * i * log1m(p^2) correction below\n    real a = eta + 0.5 * (K - 1);\n    int raw_idx = 1;\n\n    // tree 1: marginal correlations with variable 1\n    for (k in 2:K) {\n      if (is_zero_scan(k, 1, zeros)) {\n        P[1, k] = 0;  // prior terms at p = 0 are constants\n      } else {\n        P[1, k] = lower_upper_bound_jacobian(raw[raw_idx], -1, 1);\n        raw_idx += 1;\n        jacobian += beta_lpdf(0.5 * (P[1, k] + 1) | a, a)\n                    - 0.5 * log1m(P[1, k]^2);\n      }\n      C[1, k] = P[1, k];\n      C[k, 1] = P[1, k];\n    }\n\n    for (i in 2:(K - 1)) {\n      for (j in (i + 1):K) {\n        vector[i - 1] b1;\n        vector[i - 1] b2;\n        int m = i;\n        for (k in 1:(i - 1)) {\n          m -= 1;\n          b1[k] = P[m, i] * P[m, j];\n          b2[k] = sqrt((1 - P[m, i]^2) * (1 - P[m, j]^2));\n        }\n        // unwinding the partial correlation recursion is affine:\n        // C[i, j] = A + B * P[i, j]\n        real A = 0;\n        real B = 1;\n        for (k in 1:(i - 1)) {\n          A = b1[k] + A * b2[k];\n          B *= b2[k];\n        }\n        real p_ij;\n        if (is_zero_scan(j, i, zeros)) {\n          p_ij = -A / B;         // C[i, j] = 0\n          jacobian += -log(B);   // delta in Omega coords -> partial coords\n        } else {\n          p_ij = lower_upper_bound_jacobian(raw[raw_idx], -1, 1);\n          raw_idx += 1;\n        }\n        // LKJ prior on the tree-i partial (evaluated at p* for zeros)\n        jacobian += beta_lpdf(0.5 * (p_ij + 1) | a, a)\n                    - 0.5 * i * log1m(p_ij^2);\n        P[i, j] = p_ij;\n        C[i, j] = A + B * p_ij;\n        C[j, i] = C[i, j];\n      }\n    }\n    return C;\n  }\n}\ndata {\n  int<lower=2> K;                             // dimension of correlation matrix\n  real<lower=0> eta;                          // concentration in LKJ\n  int<lower=0, upper=choose(K, 2)> N_zero;    // # structural zero correlations\n  array[N_zero, 2] int zeros;                 // lower triangular index pairs\n}\nparameters {\n  vector[choose(K, 2) - N_zero] raw;\n}\ntransformed parameters {\n  // prior is included via the beta terms in the constraint, so the\n  // model block stays empty\n  matrix[K, K] Omega = corr_constrain_cvine_jacobian(K, raw, zeros, eta);\n}\nmodel {\n}\n\n```\n\n### cvine_lookahead\n\n``` {.stan filename=\"cvine-lookahead-corr-zeros.stan\"}\n/*\n  Look-ahead C-vine parameterization of a correlation matrix with exact structural\n  zeros. This is the equality-specialized interface to the look-ahead C-vine\n  transform in https://gist.github.com/spinkney/7d994fb03079c9edb8a0e83a40d2faad.\n\n  Each structural zero is an exact ordinary-correlation equality and consumes\n  no element of `raw`. All other ordinary correlations have bounds (-1, 1).\n  The transform accumulates the reduced raw-to-free-correlation Jacobian, and\n  the model adds the LKJ determinant kernel with respect to those free cells.\n*/\n\nfunctions {\n  // sqrt((1-a^2)(1-b^2)), evaluated stably on [-1,1]^2.\n  real unit_circle_root_product(real a, real b) {\n    real q = (1 - a) * (1 + a) * (1 - b) * (1 + b);\n    return sqrt(fmax(0.0, q));\n  }\n\n  /*\n    Exact projection of the 3 x 3 correlation elliptope. Let x be the\n    correlation to project, with y in [y_lo, y_hi] and r in [r_lo, r_hi].\n    The result is [minimum feasible x, maximum feasible x]. Degenerate point\n    intervals are retained for exact zero constraints.\n  */\n  vector corr3_project_first(real y_lo_in, real y_hi_in,\n                             real r_lo_in, real r_hi_in) {\n    real y_lo = fmax(-1.0, fmin(1.0, y_lo_in));\n    real y_hi = fmax(-1.0, fmin(1.0, y_hi_in));\n    real r_lo = fmax(-1.0, fmin(1.0, r_lo_in));\n    real r_hi = fmax(-1.0, fmin(1.0, r_hi_in));\n    real x_lo;\n    real x_hi;\n    vector[2] out;\n\n    if (y_lo > y_hi || r_lo > r_hi) {\n      reject(\"corr3_project_first received a reversed interval: y=[\",\n             y_lo, \",\", y_hi, \"], r=[\", r_lo, \",\", r_hi, \"].\");\n    }\n\n    // Maximum x.\n    if (fmax(y_lo, r_lo) <= fmin(y_hi, r_hi)) {\n      x_hi = 1.0;\n    } else if (y_lo > r_hi) {\n      x_hi = y_lo * r_hi + unit_circle_root_product(y_lo, r_hi);\n    } else {\n      x_hi = y_hi * r_lo + unit_circle_root_product(y_hi, r_lo);\n    }\n\n    // Minimum x.\n    if (fmax(y_lo, -r_hi) <= fmin(y_hi, -r_lo)) {\n      x_lo = -1.0;\n    } else if (y_lo > -r_lo) {\n      x_lo = y_lo * r_lo - unit_circle_root_product(y_lo, r_lo);\n    } else {\n      x_lo = y_hi * r_hi - unit_circle_root_product(y_hi, r_hi);\n    }\n\n    out[1] = fmax(-1.0, fmin(1.0, x_lo));\n    out[2] = fmax(-1.0, fmin(1.0, x_hi));\n    return out;\n  }\n\n  /*\n    Map unconstrained free coordinates to a box-constrained correlation\n    matrix while solving exact ordinary-correlation equalities. The complete\n    reduced raw -> free ordinary-correlation Jacobian is accumulated here.\n  */\n  tuple(matrix, real) cvine_bound_equality_jacobian(\n      vector raw,\n      matrix corr_lower,\n      matrix corr_upper,\n      real interval_tolerance,\n      real validation_tolerance) {\n    int K = rows(corr_lower);\n    int M_free = num_elements(raw);\n    int pos_free = 1;\n    array[K, K] int pair_is_free = rep_array(0, K, K);\n    matrix[K, K] lo_work = corr_lower;\n    matrix[K, K] hi_work = corr_upper;\n    matrix[K, K] P_work = identity_matrix(K);\n    matrix[K, K] C_work = identity_matrix(K);\n    real logJ = 0.0;\n    real logdet = 0.0;\n\n    if (cols(corr_lower) != K\n        || rows(corr_upper) != K\n        || cols(corr_upper) != K) {\n      reject(\"cvine_bound_equality_transform requires equally sized square \",\n             \"bound matrices.\");\n    }\n\n    // Classify coordinates and prepare the initial conditional bounds.\n    for (i in 1:K) {\n      lo_work[i, i] = 1.0;\n      hi_work[i, i] = 1.0;\n\n      if (i > 1) {\n        for (j in 1:(i - 1)) {\n          real width = corr_upper[i, j] - corr_lower[i, j];\n          real lo_ij = corr_lower[i, j];\n          real hi_ij = corr_upper[i, j];\n\n          if (width > 0.0) {\n            pair_is_free[i, j] = 1;\n            pair_is_free[j, i] = 1;\n            lo_ij = fmax(-1.0, corr_lower[i, j]);\n            hi_ij = fmin(1.0, corr_upper[i, j]);\n          } else if (width == 0.0) {\n            // Preserve a point equality exactly.\n            lo_ij = corr_lower[i, j];\n            hi_ij = corr_lower[i, j];\n          } else {\n            reject(\"cvine_bound_equality_transform received a reversed \",\n                   \"interval at pair (\", i, \",\", j, \"): [\",\n                   corr_lower[i, j], \",\", corr_upper[i, j], \"].\");\n          }\n\n          lo_work[i, j] = lo_ij;\n          lo_work[j, i] = lo_ij;\n          hi_work[i, j] = hi_ij;\n          hi_work[j, i] = hi_ij;\n        }\n      }\n    }\n\n    // Sequential C-vine construction.\n    for (i in 1:(K - 1)) {\n      for (j in (i + 1):K) {\n        int is_free = pair_is_free[i, j];\n        real lo_direct = lo_work[i, j];\n        real hi_direct = hi_work[i, j];\n        real lo = fmax(-1.0, lo_direct);\n        real hi = fmin(1.0, hi_direct);\n        real x;\n        real log_scale = 0.0;\n\n        // d C[i,j] / d P[i,j], holding earlier C-vine rows fixed.\n        if (i > 1) {\n          for (m in 1:(i - 1)) {\n            log_scale += 0.5 * (\n                log1m(square(P_work[m, i]))\n                + log1m(square(P_work[m, j])));\n          }\n        }\n\n        if (is_free == 1) {\n          real width;\n\n          // Intersect the direct interval with every 3 x 3 projection.\n          if (j < K) {\n            for (k in (j + 1):K) {\n              vector[2] projected = corr3_project_first(\n                  lo_work[i, k], hi_work[i, k],\n                  lo_work[j, k], hi_work[j, k]);\n              lo = fmax(lo, projected[1]);\n              hi = fmin(hi, projected[2]);\n            }\n          }\n\n          width = hi - lo;\n          if (!(width > interval_tolerance)) {\n            reject(\"Empty free C-vine interval at partial pair (\", i, \",\", j,\n                   \"). Interval after look-ahead=[\", lo, \",\", hi, \"].\");\n          }\n          if (pos_free > M_free) {\n            reject(\"cvine_bound_equality_transform received too few raw \",\n                   \"coordinates; missing the coordinate for pair (\", i, \",\",\n                   j, \").\");\n          }\n\n          {\n            real q = inv_logit(raw[pos_free]);\n\n            if (!(q > 0.0 && q < 1.0)) {\n              reject(\"inv_logit(raw[\", pos_free,\n                     \"]) numerically reached an endpoint; raw=\",\n                     raw[pos_free], \".\");\n            }\n\n            x = lo + width * q;\n            logJ += log(width)\n                    + log_inv_logit(raw[pos_free])\n                    + log1m_inv_logit(raw[pos_free])\n                    + log_scale;\n          }\n\n          pos_free += 1;\n        } else {\n          real fixed_x = 0.5 * (lo_direct + hi_direct);\n\n          if (abs(hi_direct - lo_direct) > validation_tolerance) {\n            reject(\"Internal equality interval acquired nonzero width at pair (\",\n                   i, \",\", j, \"): [\", lo_direct, \",\", hi_direct, \"].\");\n          }\n          if (!(fixed_x > -1.0 && fixed_x < 1.0)) {\n            reject(\"Exact equality implies a non-interior partial correlation \",\n                   \"at pair (\", i, \",\", j, \"): \", fixed_x, \".\");\n          }\n\n          // Validate rather than alter the exact point during look-ahead.\n          if (j < K) {\n            for (k in (j + 1):K) {\n              vector[2] projected = corr3_project_first(\n                  lo_work[i, k], hi_work[i, k],\n                  lo_work[j, k], hi_work[j, k]);\n\n              if (fixed_x < projected[1] - validation_tolerance\n                  || fixed_x > projected[2] + validation_tolerance) {\n                reject(\"Exact equality partial at pair (\", i, \",\", j,\n                       \") is incompatible with future pair \", k,\n                       \". Fixed partial=\", fixed_x,\n                       \", projected interval=[\", projected[1], \",\",\n                       projected[2], \"].\");\n              }\n            }\n          }\n\n          x = fixed_x;\n        }\n\n        P_work[i, j] = x;\n        P_work[j, i] = x;\n        logdet += log1m(square(x));\n\n        // Update future intervals in the current C-vine row.\n        if (j < K) {\n          for (k in (j + 1):K) {\n            vector[2] future_projected = corr3_project_first(\n                x, x, lo_work[j, k], hi_work[j, k]);\n\n            if (pair_is_free[i, k] == 1) {\n              real next_lo = fmax(lo_work[i, k], future_projected[1]);\n              real next_hi = fmin(hi_work[i, k], future_projected[2]);\n\n              if (!(next_hi - next_lo > interval_tolerance)) {\n                reject(\"Future free C-vine interval became empty after partial (\",\n                       i, \",\", j, \"). Future pair=\", i, \",\", k,\n                       \", interval=[\", next_lo, \",\", next_hi, \"].\");\n              }\n\n              lo_work[i, k] = next_lo;\n              lo_work[k, i] = next_lo;\n              hi_work[i, k] = next_hi;\n              hi_work[k, i] = next_hi;\n            } else {\n              real fixed_future = 0.5 * (\n                  lo_work[i, k] + hi_work[i, k]);\n\n              if (abs(hi_work[i, k] - lo_work[i, k])\n                  > validation_tolerance) {\n                reject(\"Internal future equality interval acquired width at \",\n                       \"pair (\", i, \",\", k, \").\");\n              }\n              if (fixed_future < future_projected[1] - validation_tolerance\n                  || fixed_future > future_projected[2]\n                                      + validation_tolerance) {\n                reject(\"Sampling partial (\", i, \",\", j,\n                       \") made exact future equality pair (\", i, \",\", k,\n                       \") infeasible. Fixed future partial=\", fixed_future,\n                       \", projected interval=[\", future_projected[1], \",\",\n                       future_projected[2], \"].\");\n              }\n\n              lo_work[i, k] = fixed_future;\n              lo_work[k, i] = fixed_future;\n              hi_work[i, k] = fixed_future;\n              hi_work[k, i] = fixed_future;\n            }\n          }\n        }\n      }\n\n      // Propagate remaining intervals to the next C-vine level.\n      if (i < K - 1) {\n        for (j in (i + 1):(K - 1)) {\n          for (k in (j + 1):K) {\n            real pij = P_work[i, j];\n            real pik = P_work[i, k];\n            real denom = sqrt((1 - square(pij)) * (1 - square(pik)));\n\n            if (!(denom > 0.0)) {\n              reject(\"Zero conditional-correlation denominator at level \", i,\n                     \" for pair (\", j, \",\", k, \").\");\n            }\n\n            if (pair_is_free[j, k] == 1) {\n              real next_lo = fmax(\n                  -1.0, (lo_work[j, k] - pij * pik) / denom);\n              real next_hi = fmin(\n                  1.0, (hi_work[j, k] - pij * pik) / denom);\n\n              if (!(next_hi - next_lo > interval_tolerance)) {\n                reject(\"Conditional free box became empty after C-vine row \",\n                       i, \" for pair (\", j, \",\", k, \"). Interval=[\",\n                       next_lo, \",\", next_hi, \"].\");\n              }\n\n              lo_work[j, k] = next_lo;\n              lo_work[k, j] = next_lo;\n              hi_work[j, k] = next_hi;\n              hi_work[k, j] = next_hi;\n            } else {\n              real fixed_current = 0.5 * (\n                  lo_work[j, k] + hi_work[j, k]);\n              real fixed_next;\n\n              if (abs(hi_work[j, k] - lo_work[j, k])\n                  > validation_tolerance) {\n                reject(\"Internal equality interval acquired width before \",\n                       \"conditioning at pair (\", j, \",\", k, \").\");\n              }\n\n              fixed_next = (fixed_current - pij * pik) / denom;\n              if (!(fixed_next > -1.0 && fixed_next < 1.0)) {\n                reject(\"Exact ordinary equality implies a non-interior \",\n                       \"conditional correlation after level \", i,\n                       \" for pair (\", j, \",\", k, \"): \", fixed_next, \".\");\n              }\n\n              lo_work[j, k] = fixed_next;\n              lo_work[k, j] = fixed_next;\n              hi_work[j, k] = fixed_next;\n              hi_work[k, j] = fixed_next;\n            }\n          }\n        }\n      }\n    }\n\n    if (pos_free != M_free + 1) {\n      reject(\"cvine_bound_equality_transform received \", M_free,\n             \" raw coordinates but consumed \", pos_free - 1, \".\");\n    }\n\n    // Convert C-vine partial correlations to ordinary correlations.\n    for (i in 1:(K - 1)) {\n      for (j in (i + 1):K) {\n        real value = P_work[i, j];\n\n        if (i > 1) {\n          int m = i;\n          for (step in 1:(i - 1)) {\n            m -= 1;\n            value = P_work[m, i] * P_work[m, j]\n                    + value\n                      * sqrt((1 - square(P_work[m, i]))\n                             * (1 - square(P_work[m, j])));\n          }\n        }\n\n        C_work[i, j] = value;\n        C_work[j, i] = value;\n      }\n    }\n\n    jacobian += logJ;\n    return (C_work, logdet);\n  }\n}\n\ndata {\n  int<lower=2> K;                             // dimension of correlation matrix\n  real<lower=0> eta;                          // LKJ concentration\n  int<lower=0, upper=choose(K, 2)> N_zero;    // # structural zero correlations\n  array[N_zero, 2] int zeros;                 // lower triangular index pairs\n}\n\ntransformed data {\n  matrix[K, K] corr_lower = rep_matrix(-1.0, K, K);\n  matrix[K, K] corr_upper = rep_matrix(1.0, K, K);\n\n  for (i in 1:K) {\n    corr_lower[i, i] = 1.0;\n    corr_upper[i, i] = 1.0;\n  }\n\n  if (N_zero > 0) {\n    for (n in 1:N_zero) {\n      int i = zeros[n, 1];\n      int j = zeros[n, 2];\n\n      if (i < 2 || i > K || j < 1 || j >= i) {\n        reject(\"zeros[\", n, \"] must be a lower-triangular index pair; got (\",\n               i, \",\", j, \").\");\n      }\n      if (n > 1) {\n        for (m in 1:(n - 1)) {\n          if (zeros[m, 1] == i && zeros[m, 2] == j) {\n            reject(\"Duplicate structural-zero pair (\", i, \",\", j, \").\");\n          }\n        }\n      }\n\n      corr_lower[i, j] = 0.0;\n      corr_lower[j, i] = 0.0;\n      corr_upper[i, j] = 0.0;\n      corr_upper[j, i] = 0.0;\n    }\n  }\n}\n\nparameters {\n  // Exact zeros are omitted from the parameter vector.\n  vector[choose(K, 2) - N_zero] raw;\n}\n\ntransformed parameters {\n  corr_matrix[K] Omega;\n  real log_det_Omega;\n\n  {\n    tuple(matrix[K, K], real) transform = cvine_bound_equality_jacobian(\n        raw, corr_lower, corr_upper, 1e-12, 1e-10);\n    Omega = transform.1;\n    log_det_Omega = transform.2;\n  }\n}\n\nmodel {\n  // LKJ density with respect to the free ordinary-correlation coordinates.\n  target += (eta - 1.0) * log_det_Omega;\n}\n\n```\n\n### rowscale\n\n``` {.stan filename=\"pinkney-corr-zeros-rowscale.stan\"}\nfunctions {\n  int is_zero(int row_idx, int col_idx, array[,] int zeros, int zero_idx) {\n    return zero_idx <= size(zeros)\n      && zeros[zero_idx, 1] == row_idx\n      && zeros[zero_idx, 2] == col_idx;\n  }\n\n  matrix cholesky_corr_constrain_rowscale_jacobian(int K, vector raw,\n                                                   array[,] int zeros) {\n    // Samples L[i, j] directly (bounds pre-divided by L[j, j]) and keeps the\n    // remaining radius in the untouched tail of the row: each entry of\n    // L[i, j:i] holds the current radius until column j is sampled, then the\n    // tail is scaled down. L[i, i] ends up as the diagonal automatically.\n    matrix[K, K] L = rep_matrix(0, K, K);\n    int raw_idx = 1;\n    int zero_idx = 1;\n    L[1, 1] = 1;\n\n    for (i in 2:K) {\n      L[i, 1:i] = rep_row_vector(1, i);\n      for (j in 1:(i - 1)) {\n        real l_ij_old = L[i, j];  // remaining radius of row i\n        real b1 = dot_product(L[j, 1:(j - 1)], L[i, 1:(j - 1)]);\n        if (is_zero(i, j, zeros, zero_idx)) {\n          L[i, j] = -b1 / L[j, j];  // Omega[i, j] = b1 + Lij * Ljj = 0\n          jacobian += -log(L[j, j]);  // Carpenter's correction\n          zero_idx += 1;\n        } else {\n          // |L[i, j]| <= radius and Omega[i, j] = b1 + Lij * Ljj in (-1, 1);\n          // sampling L directly, the 1 / L[j, j] factor is inside the\n          // bound width, so no separate jacobian term\n          real low = max({-l_ij_old, (-1 - b1) / L[j, j]});\n          real up = min({l_ij_old, (1 - b1) / L[j, j]});\n          L[i, j] = lower_upper_bound_jacobian(raw[raw_idx], low, up);\n          raw_idx += 1;\n        }\n        L[i, (j + 1):i] *= sqrt(1 - (L[i, j] / l_ij_old)^2);\n      }\n    }\n    return L;\n  }\n}\ndata {\n  int<lower=2> K;                             // dimension of correlation matrix\n  real<lower=0> eta;                          // concentration in LKJ Cholesky\n  int<lower=0, upper=choose(K, 2)> N_zero;    // # structural zero correlations\n  array[N_zero, 2] int zeros;                 // lower triangular, row major order\n}\nparameters {\n  vector[choose(K, 2) - N_zero] raw;\n}\ntransformed parameters {\n  matrix[K, K] L_Omega = cholesky_corr_constrain_rowscale_jacobian(K, raw, zeros);\n}\nmodel {\n  L_Omega ~ lkj_corr_cholesky(eta);\n}\ngenerated quantities {\n  matrix[K, K] Omega = multiply_lower_tri_self_transpose(L_Omega);\n}\n\n```\n\n### schur\n\n``` {.stan filename=\"pinkney-corr-zeros-schur.stan\"}\nfunctions {\n  int is_zero(int row_idx, int col_idx, array[,] int zeros, int zero_idx) {\n    return zero_idx <= size(zeros)\n      && zeros[zero_idx, 1] == row_idx\n      && zeros[zero_idx, 2] == col_idx;\n  }\n\n  matrix cholesky_corr_constrain_schur_jacobian(int K, vector raw,\n                                                array[,] int zeros) {\n    // Canonical partial correlation construction: each free entry is the\n    // remaining radius times tanh(raw), so |L[i, j]| < radius automatically\n    // and no correlation bounds are needed. The untouched tail of each row\n    // holds the current radius (row-scaling trick).\n    matrix[K, K] L = rep_matrix(0, K, K);\n    int raw_idx = 1;\n    int zero_idx = 1;\n    L[1, 1] = 1;\n\n    for (i in 2:K) {\n      L[i, 1:i] = rep_row_vector(1, i);\n      for (j in 1:(i - 1)) {\n        real r = L[i, j];  // remaining radius of row i\n        if (is_zero(i, j, zeros, zero_idx)) {\n          real b1 = dot_product(L[j, 1:(j - 1)], L[i, 1:(j - 1)]);\n          L[i, j] = -b1 / L[j, j];  // Omega[i, j] = b1 + Lij * Ljj = 0\n          jacobian += -log(L[j, j]);  // Carpenter's correction\n          zero_idx += 1;\n          L[i, (j + 1):i] *= sqrt(1 - (L[i, j] / r)^2);\n        } else {\n          real x = raw[raw_idx];\n          real cosh_x = cosh(x);\n          // tanh jacobian and x -> L[i, j] = r * tanh(x);\n          // the radius update sqrt(1 - tanh^2) is 1 / cosh\n          jacobian += -2 * log(cosh_x) + log(r);\n          L[i, j] = r * tanh(x);\n          raw_idx += 1;\n          L[i, (j + 1):i] /= cosh_x;\n        }\n      }\n    }\n    return L;\n  }\n}\ndata {\n  int<lower=2> K;                             // dimension of correlation matrix\n  real<lower=0> eta;                          // concentration in LKJ Cholesky\n  int<lower=0, upper=choose(K, 2)> N_zero;    // # structural zero correlations\n  array[N_zero, 2] int zeros;                 // lower triangular, row major order\n}\nparameters {\n  vector[choose(K, 2) - N_zero] raw;\n}\ntransformed parameters {\n  matrix[K, K] L_Omega = cholesky_corr_constrain_schur_jacobian(K, raw, zeros);\n}\nmodel {\n  L_Omega ~ lkj_corr_cholesky(eta);\n}\ngenerated quantities {\n  matrix[K, K] Omega = multiply_lower_tri_self_transpose(L_Omega);\n}\n\n```\n\n### qr\n\n``` {.stan filename=\"qr-corr-zeros.stan\"}\nfunctions {\n  matrix cholesky_corr_constrain_unitvec_jacobian(int K, vector raw,\n                                                  array[,] int zeros) {\n    // Row i of a Cholesky correlation factor is a unit vector in R^i with\n    // positive last coordinate. Omega[i, j] = 0 means row i is orthogonal\n    // to row j, so row i lives on the unit sphere in the orthogonal\n    // complement of its zero-partner rows: the constraint is satisfied\n    // exactly by construction and no proposal can ever be infeasible.\n    //\n    // Chart per row: unit vector u = (C * y, 1)' / s with s = sqrt(1 + y'y),\n    // C an orthonormal basis of the feasible subspace. Jacobian onto the\n    // subsphere is -(d + 2) * log(s); the joint delta over the row's zeros\n    // contributes -0.5 * log det(Gram) = -sum(log|diag(R)|) from the QR.\n    matrix[K, K] L = rep_matrix(0, K, K);\n    int raw_idx = 1;\n    int zero_idx = 1;\n    L[1, 1] = 1;\n\n    for (i in 2:K) {\n      int n_z = 0;\n      while (zero_idx + n_z <= size(zeros)\n             && zeros[zero_idx + n_z, 1] == i) {\n        n_z += 1;\n      }\n      int d = i - 1 - n_z;\n\n      if (n_z == 0) {\n        vector[d] y = raw[raw_idx:(raw_idx + d - 1)];\n        real s = sqrt(1 + dot_self(y));\n        L[i, 1:(i - 1)] = y' / s;\n        L[i, i] = 1 / s;\n        jacobian += -(d + 2) * log(s);\n        raw_idx += d;\n      } else {\n        // columns are the zero-partner rows restricted to 1:(i - 1)\n        matrix[i - 1, n_z] A;\n        for (n in 1:n_z) {\n          A[, n] = L[zeros[zero_idx + n - 1, 2], 1:(i - 1)]';\n        }\n        // full qr: the complement basis lives in Q's last d columns and\n        // diagonal(R) supplies the Gram term from one decomposition\n        matrix[i - 1, i - 1] Q;\n        matrix[i - 1, n_z] R;\n        (Q, R) = qr(A);\n        jacobian += -sum(log(abs(diagonal(R))));\n        if (d > 0) {\n          vector[d] y = raw[raw_idx:(raw_idx + d - 1)];\n          real s = sqrt(1 + dot_self(y));\n          L[i, 1:(i - 1)] = (Q[, (n_z + 1):(i - 1)] * y)' / s;\n          L[i, i] = 1 / s;\n          jacobian += -(d + 2) * log(s);\n          raw_idx += d;\n        } else {\n          L[i, i] = 1;  // row fully constrained: e_i\n        }\n        zero_idx += n_z;\n      }\n    }\n    return L;\n  }\n}\ndata {\n  int<lower=2> K;                             // dimension of correlation matrix\n  real<lower=0> eta;                          // concentration in LKJ Cholesky\n  int<lower=0, upper=choose(K, 2)> N_zero;    // # structural zero correlations\n  array[N_zero, 2] int zeros;                 // lower triangular, row major order\n}\nparameters {\n  vector[choose(K, 2) - N_zero] raw;\n}\ntransformed parameters {\n  matrix[K, K] L_Omega = cholesky_corr_constrain_unitvec_jacobian(K, raw, zeros);\n}\nmodel {\n  L_Omega ~ lkj_corr_cholesky(eta);\n}\ngenerated quantities {\n  matrix[K, K] Omega = multiply_lower_tri_self_transpose(L_Omega);\n}\n\n```\n\n### qr2\n\n``` {.stan filename=\"qr2-corr-zeros.stan\"}\nfunctions {\n  matrix cholesky_corr_constrain_unitvec2_jacobian(int K, vector raw,\n                                                   array[,] int zeros) {\n    // Same exact-constraint geometry as the unitvec version: row i lives on\n    // the unit sphere in the orthogonal complement of its zero-partner rows,\n    // so every raw value maps to a valid constrained matrix. The chart on\n    // the subsphere is the canonical-partial-correlation (tanh) stick\n    // construction instead of the gnomonic map, to lighten the tails.\n    matrix[K, K] L = rep_matrix(0, K, K);\n    int raw_idx = 1;\n    int zero_idx = 1;\n    L[1, 1] = 1;\n\n    for (i in 2:K) {\n      int n_z = 0;\n      while (zero_idx + n_z <= size(zeros)\n             && zeros[zero_idx + n_z, 1] == i) {\n        n_z += 1;\n      }\n      int d = i - 1 - n_z;\n\n      // subspace coordinates via tanh sticks: w_k = tanh(x_k) * radius,\n      // radius update sqrt(1 - tanh^2) = 1 / cosh, so the whole chart\n      // jacobian collapses to accumulated powers of log(cosh)\n      vector[d] w;\n      real r = 1;\n      for (k in 1:d) {\n        real x = raw[raw_idx];\n        real cosh_x = cosh(x);\n        w[k] = r * tanh(x);\n        jacobian += -(d - k + 2) * log(cosh_x);\n        r /= cosh_x;\n        raw_idx += 1;\n      }\n\n      if (n_z == 0) {\n        if (d > 0) {\n          L[i, 1:d] = w';\n        }\n        L[i, i] = r;\n      } else {\n        // columns are the zero-partner rows restricted to 1:(i - 1);\n        // -0.5 * log det(Gram) from the joint delta over this row's zeros\n        matrix[i - 1, n_z] A;\n        for (n in 1:n_z) {\n          A[, n] = L[zeros[zero_idx + n - 1, 2], 1:(i - 1)]';\n        }\n        // full qr: the complement basis lives in Q's last d columns and\n        // diagonal(R) supplies the Gram term from one decomposition\n        matrix[i - 1, i - 1] Q;\n        matrix[i - 1, n_z] R;\n        (Q, R) = qr(A);\n        jacobian += -sum(log(abs(diagonal(R))));\n        if (d > 0) {\n          L[i, 1:(i - 1)] = (Q[, (n_z + 1):(i - 1)] * w)';\n        }\n        L[i, i] = r;\n        zero_idx += n_z;\n      }\n    }\n    return L;\n  }\n}\ndata {\n  int<lower=2> K;                             // dimension of correlation matrix\n  real<lower=0> eta;                          // concentration in LKJ Cholesky\n  int<lower=0, upper=choose(K, 2)> N_zero;    // # structural zero correlations\n  array[N_zero, 2] int zeros;                 // lower triangular, row major order\n}\nparameters {\n  vector[choose(K, 2) - N_zero] raw;\n}\ntransformed parameters {\n  matrix[K, K] L_Omega = cholesky_corr_constrain_unitvec2_jacobian(K, raw, zeros);\n}\nmodel {\n  L_Omega ~ lkj_corr_cholesky(eta);\n}\ngenerated quantities {\n  matrix[K, K] Omega = multiply_lower_tri_self_transpose(L_Omega);\n}\n\n```\n:::\n",
    "supporting": [
      "corr-zeros-bakeoff_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}